Repository ChainSafe/forest, pull requests merged in 2020-11, with the labels that each got.

#797 add msgs to msg pool
  blockchain/message_pool/src/block_prob.rs
  blockchain/message_pool/src/msgpool.rs
  forest/src/daemon.rs
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/service.rs
Labels: Network, Status: Needs Review

#799 Optimize statediff and fix hamt bug
  ipld/hamt/src/pointer.rs
  utils/statediff/src/lib.rs
Labels: Status: Needs Review, Type: Bug

#802 Fix reschedule sector expirations
  vm/actor/src/builtin/miner/state.rs
Labels: Status: Needs Review, Type: Bug

#804 Fix unsealed sector padding
  vm/interpreter/src/gas_tracker/mod.rs
  vm/runtime/src/lib.rs
Labels: Status: Needs Review

#805 Update gossip messagepool error log
  Cargo.lock
  node/forest_libp2p/src/service.rs
  vm/address/src/lib.rs
Labels: Status: Needs Review, Type: Maintenance

#810 Fix message receipt json
  vm/message/src/message_receipt.rs
Labels: Status: Needs Review, Type: Bug

#812 Update proofs and other deps
  Cargo.lock
  Makefile
  blockchain/beacon/Cargo.toml
  blockchain/blocks/Cargo.toml
  blockchain/chain_sync/Cargo.toml
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/utils.rs
  crypto/Cargo.toml
  ipld/Cargo.toml
  ipld/cid/Cargo.toml
  key_management/Cargo.toml
  node/db/Cargo.toml
  node/rpc/Cargo.toml
  tests/conformance_tests/Cargo.toml
  tests/serialization_tests/Cargo.toml
  types/Cargo.toml
  utils/bitfield/Cargo.toml
  utils/commcid/Cargo.toml
  utils/test_utils/Cargo.toml
  vm/actor/Cargo.toml
  vm/interpreter/Cargo.toml
  vm/message/Cargo.toml
  vm/runtime/Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#803 Defer bitfield decoding until its first use
  Cargo.lock
  utils/bitfield/Cargo.toml
  utils/bitfield/src/lib.rs
  utils/bitfield/src/unvalidated.rs
  vm/actor/src/builtin/miner/deadline_state.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/partition_state.rs
  vm/actor/src/builtin/miner/sector_map.rs
  vm/actor/src/builtin/miner/sectors.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/miner/types.rs
Labels: Status: Needs Review, VM

#808 Process blocks coming off of GossipSub
  Cargo.lock
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/chain_sync/src/sync_worker/full_sync_test.rs
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/service.rs
Labels: Blockchain, Network, Status: Needs Review

#807 Cleanup batch_verify_seal and tipset state execution
  blockchain/message_pool/src/msgpool.rs
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/utils.rs
  forest/src/daemon.rs
  node/rpc/src/state_api.rs
  utils/genesis/src/lib.rs
  vm/actor/src/builtin/power/mod.rs
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/vm.rs
  vm/runtime/src/lib.rs
Labels: Status: Needs Review, Type: Maintenance

#809 Refactor chainstore and related components
  Cargo.lock
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/chain_sync/src/sync_worker/full_sync_test.rs
  blockchain/chain_sync/src/sync_worker/validate_block_test.rs
  blockchain/message_pool/src/msgpool.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/chain_rand.rs
  blockchain/state_manager/src/lib.rs
  forest/src/daemon.rs
  node/forest_libp2p/src/blocksync/provider.rs
  node/forest_libp2p/src/service.rs
  node/rpc/src/chain_api.rs
  node/rpc/src/gas_api.rs
  node/rpc/src/lib.rs
  node/rpc/src/mpool_api.rs
  node/rpc/src/state_api.rs
  node/rpc/src/sync_api.rs
  node/rpc/src/wallet_api.rs
  tests/conformance_tests/Cargo.toml
  tests/conformance_tests/src/rand_replay.rs
  tests/conformance_tests/src/stubs.rs
  tests/conformance_tests/src/tipset.rs
  utils/genesis/src/lib.rs
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/rand.rs
  vm/interpreter/tests/transfer_test.rs
Labels: Status: Needs Review, Type: Maintenance

#832 Fix block messages generation for sequence edge case
  Cargo.lock
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/message_pool/src/msgpool.rs
  blockchain/state_manager/src/lib.rs
  vm/interpreter/Cargo.toml
Labels: Status: Merge Ready, Type: Bug

#833 Add Gossipsub chain messages to MPool in the ChainSyncer instead of Libp2p Service
  Cargo.lock
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  forest/src/daemon.rs
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/service.rs
Labels: Blockchain, Network, Status: Needs Review

#813 CircleCI updates, removal of github actions
  .circleci/config.yml
  .github/workflows/audit.yml
  .github/workflows/ci-rust.yml
  Cargo.lock
  README.md
  codecov.yml
  scripts/build-rust-docs.sh
Labels: Status: Needs Review, Type: Maintenance

#834 Fix allow internal reset after failed tx
  vm/interpreter/src/default_runtime.rs
Labels: Status: Needs Review, Type: Bug

#831 Update README.md with security policy
  README.md
Labels: Status: Needs Review

#840 Fixes code cov build
  .circleci/config.yml
  Cargo.lock
  Makefile
  blockchain/chain_sync/src/sync.rs
  node/forest_libp2p/src/service.rs
Labels: Status: Needs Review

#843 Fix makefile test commands
  Makefile
  README.md
  utils/bitfield/src/rleplus/reader.rs
  utils/bitfield/src/rleplus/writer.rs
Labels: Status: Needs Review, Type: Bug

#844 Fix bug with import and cleanup
  Cargo.lock
  blockchain/state_manager/src/lib.rs
  forest/src/daemon.rs
  node/db/src/lib.rs
  node/db/src/memory.rs
  node/db/src/rocks.rs
  node/db/tests/mem_test.rs
  node/db/tests/rocks_test.rs
  node/db/tests/subtests/mod.rs
  utils/genesis/Cargo.toml
  utils/genesis/src/lib.rs
Labels: Status: Needs Review, Type: Bug

#845 Fix gossipsub handling to process only when in follow state
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/message_pool/src/msgpool.rs
Labels: Status: Needs Review, Type: Bug

#842 Use concrete implementations
  ipld/blockstore/src/buffered.rs
  ipld/blockstore/src/lib.rs
  ipld/blockstore/src/tracking.rs
  ipld/cid/src/lib.rs
  vm/interpreter/src/gas_block_store.rs
Labels: Status: Needs Review, Type: Maintenance

#732 Add Networking and Republishing logic to MsgPool
  Cargo.lock
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/message_pool/Cargo.toml
  blockchain/message_pool/src/lib.rs
  blockchain/message_pool/src/msg_chain.rs
  blockchain/message_pool/src/msgpool.rs
  forest/src/daemon.rs
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/lib.rs
  node/forest_libp2p/src/service.rs
  node/rpc/src/sync_api.rs
Labels: Blockchain, Status: Needs Review

#847 Update amt for_each caching mechanisms and usages
  Cargo.lock
  ipld/amt/Cargo.toml
  ipld/amt/src/amt.rs
  ipld/amt/src/node.rs
  ipld/amt/src/value_mut.rs
  ipld/amt/tests/amt_tests.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/miner/expiration_queue.rs
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/gas_tracker/price_list.rs
Labels: Interop, Status: Needs Review

#849 Fix: update balance table
  vm/actor/src/util/balance_table.rs
  vm/actor/tests/balance_table_test.rs
Labels: Interop, Status: Needs Review

#851 Refactor ChainStore, tipset usage, cache loaded tipsets
  Cargo.lock
  blockchain/blocks/src/tipset.rs
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/tip_index.rs
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/chain_sync/src/sync_worker/full_sync_test.rs
  blockchain/chain_sync/src/sync_worker/validate_block_test.rs
  blockchain/message_pool/src/msgpool.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/chain_rand.rs
  blockchain/state_manager/src/lib.rs
  node/forest_libp2p/src/blocksync/message.rs
  node/forest_libp2p/src/blocksync/provider.rs
  node/forest_libp2p/src/service.rs
  node/rpc/src/chain_api.rs
  node/rpc/src/gas_api.rs
  node/rpc/src/mpool_api.rs
  node/rpc/src/state_api.rs
  utils/genesis/src/lib.rs
Labels: Status: Needs Review, Type: Enhancement

#852 Rename BlockSync -> ChainExchange and tweak parameters
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/peer_manager.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync_state.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/chain_sync/src/sync_worker/full_sync_test.rs
  ipld/graphsync/src/libp2p/handler.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/blocksync/mod.rs
  node/forest_libp2p/src/chain_exchange/message.rs
  node/forest_libp2p/src/chain_exchange/mod.rs
  node/forest_libp2p/src/chain_exchange/provider.rs
  node/forest_libp2p/src/hello/message.rs
  node/forest_libp2p/src/hello/mod.rs
  node/forest_libp2p/src/lib.rs
  node/forest_libp2p/src/rpc/mod.rs
  node/forest_libp2p/src/service.rs
  node/forest_libp2p/tests/decode_test.rs
  utils/test_utils/src/chain_structures.rs
Labels: Spec Change, Status: Needs Review, Type: Maintenance

#848 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Status: Needs Review, Type: Maintenance

#850 Use upstream cid
  Cargo.lock
  blockchain/blocks/src/header/mod.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/bucket.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/message_pool/src/msgpool.rs
  encoding/src/cbor.rs
  ipld/blockstore/src/buffered.rs
  ipld/blockstore/src/lib.rs
  ipld/blockstore/src/resolve.rs
  ipld/blockstore/src/tracking.rs
  ipld/car/src/util.rs
  ipld/cid/Cargo.toml
  ipld/cid/src/codec.rs
  ipld/cid/src/error.rs
  ipld/cid/src/lib.rs
  ipld/cid/src/prefix.rs
  ipld/cid/src/to_cid.rs
  ipld/cid/src/version.rs
  ipld/cid/tests/base_cid_tests.rs
  ipld/cid/tests/serde_tests.rs
  ipld/tests/cbor_test.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/hello/message.rs
  node/rpc/src/sync_api.rs
  utils/commcid/src/lib.rs
  utils/commcid/tests/commcid_tests.rs
  utils/test_utils/src/chain_structures.rs
  vm/actor/src/builtin/codes.rs
  vm/actor/src/builtin/market/deal.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/policy.rs
  vm/src/lib.rs
  vm/state_tree/tests/state_tree_tests.rs
Labels: IPLD, Status: Needs Review

#853 Switch param deserialization to the runtime to interop
  tests/conformance_tests/tests/conformance_runner.rs
  types/src/version.rs
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/verifreg/mod.rs
  vm/actor/src/util/chaos/mod.rs
  vm/actor/tests/common/mod.rs
  vm/interpreter/src/default_runtime.rs
  vm/runtime/src/lib.rs
Labels: Interop, Status: Needs Review

#857 Setup mocking panic handling in vm
  ipld/amt/src/node.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/lib.rs
  vm/actor/tests/common/mod.rs
  vm/interpreter/src/default_runtime.rs
  vm/src/exit_code.rs
Labels: Interop, Status: Needs Review

#811 Allow importing snapshot from URL + Progress bar (#762)
  Cargo.lock
  Cargo.toml
  forest/Cargo.toml
  forest/src/cli/mod.rs
  forest/src/daemon.rs
  utils/genesis/Cargo.toml
  utils/genesis/src/lib.rs
  utils/net_utils/Cargo.toml
  utils/net_utils/src/download.rs
  utils/net_utils/src/lib.rs
  utils/paramfetch/Cargo.toml
  utils/paramfetch/src/lib.rs
Labels: Status: Needs Changes, Type: Enhancement

#859 Update dependencies
  Cargo.lock
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/message_pool/src/msgpool.rs
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/utils.rs
  ipld/amt/src/amt.rs
  ipld/amt/src/node.rs
  ipld/blockstore/src/resolve.rs
  ipld/hamt/src/node.rs
  node/db/src/lib.rs
  node/rpc/src/state_api.rs
  utils/auth/src/lib.rs
  utils/paramfetch/src/lib.rs
  utils/statediff/src/lib.rs
  vm/actor/src/builtin/miner/policy.rs
  vm/actor/src/util/multimap.rs
Labels: Status: Needs Review, Type: Maintenance

#855 Implement chain index
  Cargo.lock
  blockchain/beacon/src/drand.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/index.rs
  blockchain/chain/src/store/mod.rs
  blockchain/chain/src/store/tests/tip_index_tests.rs
  blockchain/chain/src/store/tip_index.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/message_pool/src/msgpool.rs
  node/rpc/src/chain_api.rs
  utils/genesis/src/lib.rs
  utils/test_utils/src/chain_structures.rs
  vm/state_tree/Cargo.toml
  vm/state_tree/src/lib.rs
Labels: Status: Needs Review, Type: Enhancement

#856 MessagePool Greedy Message Selection
  blockchain/message_pool/src/config.rs
  blockchain/message_pool/src/lib.rs
  blockchain/message_pool/src/msg_chain.rs
  blockchain/message_pool/src/msgpool/mod.rs
  blockchain/message_pool/src/msgpool/selection.rs
Labels: Blockchain, Status: Needs Review

#858 Add sled backend and cleanup RocksDb type
  Cargo.lock
  blockchain/chain/src/store/chain_store.rs
  forest/Cargo.toml
  forest/src/daemon.rs
  ipld/blockstore/Cargo.toml
  ipld/blockstore/src/lib.rs
  ipld/blockstore/src/sled.rs
  node/db/Cargo.toml
  node/db/src/errors.rs
  node/db/src/lib.rs
  node/db/src/rocks.rs
  node/db/src/sled.rs
  node/db/tests/rocks_test.rs
  node/db/tests/sled_test.rs
Labels: Status: Needs Review, Type: Enhancement

#861 Implement chain export functionality and car writer
  Cargo.lock
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/errors.rs
  blockchain/chain_sync/src/sync_worker/full_sync_test.rs
  blockchain/chain_sync/src/sync_worker/validate_block_test.rs
  blockchain/message_pool/src/msgpool/mod.rs
  blockchain/message_pool/src/msgpool/selection.rs
  forest/src/daemon.rs
  ipld/car/Cargo.toml
  ipld/car/src/error.rs
  ipld/car/src/lib.rs
  ipld/car/src/util.rs
  ipld/car/tests/car_file_test.rs
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/chain_exchange/provider.rs
  tests/conformance_tests/Cargo.toml
  tests/conformance_tests/tests/conformance_runner.rs
  utils/genesis/Cargo.toml
  utils/genesis/src/lib.rs
  utils/net_utils/src/download.rs
Labels: Status: Needs Review, Type: Enhancement

#865 Fix unlock unvested funds
  vm/actor/src/builtin/miner/policy.rs
  vm/actor/src/builtin/miner/vesting_state.rs
Labels: Interop, Status: Needs Review

#866 Fix exit code handling in market
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/state.rs
Labels: Interop, Status: Needs Review

#868 Fork serde_bytes to disallow string and array deserialization
  Cargo.lock
  encoding/Cargo.toml
  ipld/cid/Cargo.toml
  ipld/hamt/Cargo.toml
  utils/bigint/Cargo.toml
  utils/bitfield/Cargo.toml
Labels: Interop, Status: Needs Review

#841 Rpc fixes and implementations
  Cargo.lock
  blockchain/beacon/src/drand.rs
  blockchain/beacon/src/lib.rs
  blockchain/blocks/src/tipset.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/message_pool/Cargo.toml
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  crypto/src/signature.rs
  forest/src/daemon.rs
  ipld/cid/Cargo.toml
  key_management/src/keystore.rs
  key_management/src/wallet.rs
  node/rpc/Cargo.toml
  node/rpc/src/auth_api.rs
  node/rpc/src/beacon_api.rs
  node/rpc/src/chain_api.rs
  node/rpc/src/gas_api.rs
  node/rpc/src/lib.rs
  node/rpc/src/mpool_api.rs
  node/rpc/src/state_api.rs
  node/rpc/src/sync_api.rs
  node/rpc/src/wallet_api.rs
  types/src/sector/post.rs
  types/src/version.rs
  utils/bigint/src/bigint_ser.rs
  utils/commcid/Cargo.toml
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/power/state.rs
  vm/address/Cargo.toml
  vm/address/src/lib.rs
Labels: RPC

#870 Update message json format to match Lotus
  ipld/cid/src/json.rs
  vm/address/src/lib.rs
  vm/message/Cargo.toml
  vm/message/src/signed_message.rs
  vm/message/src/unsigned_message.rs
  vm/message/tests/message_json_test.rs
Labels: Interop, Status: Needs Review

#873 Fix syncing regressions from #841
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/state_manager/src/lib.rs
Labels: Status: Needs Review, Type: Bug

#871 Implement Amt fuzzer
  ipld/amt/Cargo.toml
  ipld/amt/fuzz/.gitignore
  ipld/amt/fuzz/Cargo.toml
  ipld/amt/fuzz/fuzz_targets/amt_fuzz.rs
  ipld/amt/src/amt.rs
Labels: Status: Needs Review, Type: Enhancement

#872 Implement hamt fuzzer
  ipld/hamt/fuzz/.gitignore
  ipld/hamt/fuzz/Cargo.toml
  ipld/hamt/fuzz/fuzz_targets/hamt_fuzz.rs
Labels: Status: Needs Review
