Repository ChainSafe/forest, pull requests merged in 2020-04, with the labels that each got.

#326 Libp2p and dependency update
  blockchain/blocks/Cargo.toml
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/peer_manager.rs
  crypto/Cargo.toml
  crypto/src/signature.rs
  crypto/src/vrf.rs
  forest/Cargo.toml
  ipld/amt/Cargo.toml
  ipld/hamt/Cargo.toml
  node/clock/Cargo.toml
  node/db/Cargo.toml
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/rpc/behaviour.rs
  node/forest_libp2p/src/rpc/handler.rs
  node/forest_libp2p/src/rpc/protocol.rs
  node/forest_libp2p/src/service.rs
  node/forest_libp2p/tests/rpc_test_utils.rs
  tests/serialization_tests/Cargo.toml
  utils/rleplus/Cargo.toml
  vm/Cargo.toml
  vm/actor/Cargo.toml
  vm/address/Cargo.toml
  vm/interpreter/Cargo.toml
  vm/message/Cargo.toml
  vm/state_tree/Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#328 Logging level config with RUST_LOG env variable
  forest/src/logger/mod.rs
Labels: Node, Status: Needs Review

#293 Initial chainsync process
  Cargo.toml
  blockchain/blocks/Cargo.toml
  blockchain/blocks/src/header.rs
  blockchain/blocks/src/ticket.rs
  blockchain/blocks/src/tipset.rs
  blockchain/blocks/tests/ticket_test.rs
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/errors.rs
  blockchain/chain/src/store/tests/tip_index_tests.rs
  blockchain/chain/src/store/tip_index.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/bucket.rs
  blockchain/chain_sync/src/errors.rs
  blockchain/chain_sync/src/lib.rs
  blockchain/chain_sync/src/manager.rs
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/chain_sync/tests/manager_test.rs
  blockchain/chain_sync/tests/syncer_test.rs
  crypto/src/signature.rs
  forest/src/main.rs
  ipld/cid/src/lib.rs
  node/forest_libp2p/src/blocksync/message.rs
  node/forest_libp2p/src/config.rs
  node/forest_libp2p/src/lib.rs
  utils/test_utils/Cargo.toml
  utils/test_utils/src/chain_structures.rs
  utils/test_utils/src/lib.rs
Labels: Blockchain, Status: Needs Changes

#330 Market actor state
  vm/actor/src/builtin/market/deal.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/market/policy.rs
  vm/actor/src/builtin/market/state.rs
  vm/actor/src/builtin/mod.rs
  vm/actor/src/util/mod.rs
  vm/actor/src/util/optional_epoch.rs
Labels: Status: Needs Review, VM

#325 Miner state
  blockchain/state_manager/src/lib.rs
  ipld/amt/src/amt.rs
  ipld/amt/src/node.rs
  ipld/hamt/src/hamt.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/lib.rs
  vm/actor/src/util/balance_table.rs
  vm/actor/src/util/multimap.rs
  vm/actor/src/util/set.rs
  vm/actor/src/util/set_multimap.rs
  vm/actor/tests/multimap_test.rs
  vm/actor/tests/set_multimap_test.rs
  vm/src/sector/mod.rs
Labels: Status: Needs Review, VM

#331 Move bigint serialization utils
  Cargo.toml
  blockchain/blocks/Cargo.toml
  blockchain/blocks/src/ticket.rs
  blockchain/chain/Cargo.toml
  blockchain/chain_sync/Cargo.toml
  crypto/src/signature.rs
  crypto/src/vrf.rs
  encoding/src/bytes.rs
  encoding/src/lib.rs
  ipld/amt/src/bitmap.rs
  ipld/amt/src/root.rs
  ipld/cid/src/lib.rs
  ipld/hamt/Cargo.toml
  ipld/hamt/src/bitfield.rs
  node/db/tests/subtests/mod.rs
  node/forest_libp2p/Cargo.toml
  tests/serialization_tests/Cargo.toml
  utils/bigint/Cargo.toml
  utils/bigint/src/bigint_ser.rs
  utils/bigint/src/biguint_ser.rs
  utils/bigint/src/lib.rs
  utils/rleplus/Cargo.toml
  utils/test_utils/Cargo.toml
  vm/Cargo.toml
  vm/actor/Cargo.toml
  vm/actor/src/builtin/paych/types.rs
  vm/address/src/lib.rs
  vm/default_runtime/Cargo.toml
  vm/interpreter/Cargo.toml
  vm/message/Cargo.toml
  vm/src/method.rs
  vm/src/piece.rs
  vm/src/sector/serde.rs
  vm/state_tree/Cargo.toml
  vm/tests/params_test.rs
Labels: Status: Needs Review, Type: Maintenance

#318 Reward Actor
  vm/actor/src/builtin/power/policy.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/reward/state.rs
  vm/actor/src/builtin/reward/types.rs
  vm/actor/src/util/multimap.rs
  vm/actor/tests/multimap_test.rs
  vm/src/error.rs
Labels: Status: Merge Ready, VM

#335 Update peerid serialization in miner actor
  vm/actor/src/builtin/miner/state.rs
Labels: Status: Needs Review, VM

#333 Key hashing compatibility
  ipld/hamt/src/hash.rs
  ipld/hamt/src/lib.rs
  ipld/hamt/tests/hamt_tests.rs
  vm/actor/src/builtin/init/state.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/multisig/state.rs
  vm/actor/src/builtin/multisig/types.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/builtin/reward/state.rs
  vm/actor/src/lib.rs
  vm/actor/src/util/balance_table.rs
  vm/actor/src/util/multimap.rs
  vm/actor/src/util/set.rs
  vm/actor/src/util/set_multimap.rs
  vm/actor/tests/multimap_test.rs
  vm/actor/tests/set_test.rs
  vm/address/src/lib.rs
  vm/state_tree/src/lib.rs
Labels: Status: Needs Review, VM

#336 Refactor error handling
  blockchain/blocks/Cargo.toml
  blockchain/blocks/src/errors.rs
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/errors.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/errors.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/errors.rs
  blockchain/state_manager/src/lib.rs
  crypto/Cargo.toml
  crypto/src/errors.rs
  encoding/Cargo.toml
  encoding/src/errors.rs
  ipld/Cargo.toml
  ipld/amt/Cargo.toml
  ipld/amt/src/amt.rs
  ipld/amt/src/error.rs
  ipld/amt/src/node.rs
  ipld/blockstore/src/lib.rs
  ipld/car/Cargo.toml
  ipld/car/src/error.rs
  ipld/cid/Cargo.toml
  ipld/cid/src/error.rs
  ipld/hamt/Cargo.toml
  ipld/hamt/src/error.rs
  ipld/src/error.rs
  node/db/Cargo.toml
  node/db/src/errors.rs
  node/db/src/rocks.rs
  vm/address/Cargo.toml
  vm/address/src/errors.rs
  vm/address/tests/address_test.rs
Labels: Status: Needs Review, Type: Maintenance

#338 Market actor implementation
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/market/deal.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/market/policy.rs
  vm/actor/src/builtin/market/state.rs
  vm/actor/src/builtin/market/types.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/default_runtime/src/lib.rs
  vm/runtime/src/lib.rs
Labels: Status: Needs Review, VM

#342 Connect remaining Actor invocations to runtime and cleanup
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/system/mod.rs
  vm/default_runtime/src/lib.rs
  vm/src/exit_code.rs
Labels: Status: Needs Review, VM

#350 VM gas usage implementation and refactor
  blockchain/blocks/src/header.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/errors.rs
  blockchain/chain_sync/src/bucket.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/src/lib.rs
  encoding/src/cbor.rs
  ipld/amt/src/amt.rs
  ipld/amt/src/error.rs
  ipld/amt/src/node.rs
  ipld/blockstore/src/lib.rs
  ipld/cid/src/lib.rs
  ipld/cid/tests/base_cid_tests.rs
  ipld/cid/tests/serde_tests.rs
  ipld/hamt/src/error.rs
  ipld/hamt/src/hamt.rs
  ipld/hamt/src/hash_bits.rs
  ipld/hamt/src/node.rs
  ipld/hamt/src/pointer.rs
  ipld/tests/ipld_test.rs
  utils/test_utils/src/chain_structures.rs
  vm/Cargo.toml
  vm/actor/src/builtin/paych/mod.rs
  vm/default_runtime/Cargo.toml
  vm/default_runtime/src/gas_block_store.rs
  vm/default_runtime/src/gas_syscalls.rs
  vm/default_runtime/src/lib.rs
  vm/default_runtime/tests/transfer_test.rs
  vm/interpreter/src/lib.rs
  vm/message/src/lib.rs
  vm/message/src/signed_message.rs
  vm/message/src/unsigned_message.rs
  vm/message/tests/builder_test.rs
  vm/runtime/src/lib.rs
  vm/src/error.rs
  vm/src/gas/mod.rs
  vm/src/gas/price_list.rs
  vm/src/lib.rs
Labels: Status: Needs Review, VM

#352 Blake2b syscall
  vm/runtime/src/lib.rs
Labels: Status: Needs Review, VM

#351 Implement verify signature syscall and cleanup
  blockchain/blocks/src/errors.rs
  blockchain/blocks/src/header.rs
  blockchain/blocks/src/ticket.rs
  blockchain/chain_sync/src/errors.rs
  blockchain/chain_sync/src/sync.rs
  crypto/src/signature.rs
  crypto/src/vrf.rs
  tests/serialization_tests/tests/block_header_ser.rs
  utils/test_utils/src/chain_structures.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/runtime/src/lib.rs
Labels: Status: Needs Review, VM

#353 Implements apply_message and apply_implicit_message
  vm/default_runtime/src/lib.rs
  vm/interpreter/Cargo.toml
  vm/interpreter/src/lib.rs
  vm/src/actor_state.rs
Labels: Status: Needs Review, VM

#354 Disallow default Cid and Address serialization
  blockchain/blocks/src/header.rs
  blockchain/chain/src/store/chain_store.rs
  ipld/cid/src/lib.rs
  node/forest_libp2p/src/hello/message.rs
  node/forest_libp2p/tests/hello_test.rs
  vm/address/src/lib.rs
  vm/default_runtime/tests/transfer_test.rs
  vm/src/sector/serde.rs
  vm/state_tree/tests/state_tree_tests.rs
Labels: Status: Merge Ready, Type: Maintenance

#358 Commitment to cid conversions
  .github/workflows/ci-rust.yml
  Cargo.toml
  Makefile
  ipld/cid/src/lib.rs
  utils/commcid/Cargo.toml
  utils/commcid/src/lib.rs
  utils/commcid/tests/commcid_tests.rs
  vm/actor/src/builtin/codes.rs
Labels: Status: Needs Review, VM

#357 Update to new PoSt sector types
  vm/actor/src/builtin/miner/state.rs
  vm/default_runtime/src/gas_syscalls.rs
  vm/runtime/src/lib.rs
  vm/src/gas/price_list.rs
  vm/src/sector/post.rs
  vm/src/sector/registered_proof.rs
  vm/src/sector/seal.rs
  vm/src/sector/serde.rs
Labels: Status: Needs Review, VM

#356 Mock Runtime and tests for Account and Cron Actors
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/cron/state.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/tests/account_actor_test.rs
  vm/actor/tests/common/mod.rs
  vm/actor/tests/cron_actor_test.rs
Labels: Status: Merge Ready, VM

#359 Implement Weight method + st/gt for heaviest ts
  blockchain/blocks/src/tipset.rs
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/errors.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/Cargo.toml
  forest/Cargo.toml
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/power/policy.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/lib.rs
  vm/interpreter/src/lib.rs
Labels: Blockchain, Status: Needs Review

#370 Setup dockerfiles and update CI
  .dockerignore
  .github/workflows/ci-rust.yml
  Dockerfile
  Dockerfile-ci
  Makefile
  scripts/add_license.sh
Labels: Status: Needs Review, Type: Maintenance

#360 Compute unsealed sector CID syscall
  utils/commcid/Cargo.toml
  utils/commcid/src/lib.rs
  utils/commcid/tests/commcid_tests.rs
  vm/Cargo.toml
  vm/runtime/Cargo.toml
  vm/runtime/src/lib.rs
  vm/src/piece/mod.rs
  vm/src/piece/zero.rs
  vm/src/sector/registered_proof.rs
Labels: Status: Needs Review, VM

#329 Load Genesis from CAR file
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  forest/Cargo.toml
  forest/src/cli/config.rs
  forest/src/cli/mod.rs
  forest/src/main.rs
  ipld/car/src/lib.rs
  ipld/car/tests/devnet.car
Labels: Node, Status: Needs Changes

#369 Stmgr retrieval methods + is_ticket_winner calc for block validation
  blockchain/blocks/Cargo.toml
  blockchain/blocks/src/header.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/errors.rs
  blockchain/state_manager/src/lib.rs
  vm/actor/src/builtin/power/state.rs
  vm/default_runtime/src/lib.rs
Labels: Blockchain, Status: Needs Review

#371 Added bls aggregate sig check for block validation
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/src/lib.rs
  crypto/src/signature.rs
Labels: Blockchain, Status: Needs Review

#374 Apply Blocks and refactor
  blockchain/blocks/src/header.rs
  blockchain/blocks/src/tipset.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/network_handler.rs
  blockchain/chain_sync/src/peer_manager.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/errors.rs
  blockchain/state_manager/src/lib.rs
  ipld/blockstore/src/buffered.rs
  ipld/blockstore/src/lib.rs
  node/db/src/lib.rs
  utils/rleplus/src/bitvec_serde.rs
  vm/default_runtime/Cargo.toml
  vm/default_runtime/src/lib.rs
  vm/default_runtime/tests/transfer_test.rs
  vm/interpreter/Cargo.toml
  vm/interpreter/src/lib.rs
  vm/message/src/message_receipt.rs
  vm/src/exit_code.rs
  vm/src/lib.rs
  vm/src/state_tree.rs
  vm/state_tree/src/lib.rs
  vm/state_tree/tests/state_tree_tests.rs
Labels: Blockchain, Status: Needs Review, VM

#383 Implement buffered blockstore cache
  .github/workflows/ci-rust.yml
  ipld/blockstore/Cargo.toml
  ipld/blockstore/src/buffered.rs
Labels: IPLD, Status: Needs Review

#376 Refactor address crate
  blockchain/blocks/src/header.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/state_manager/src/lib.rs
  crypto/src/signature.rs
  node/forest_libp2p/tests/decode_test.rs
  utils/test_utils/src/chain_structures.rs
  vm/actor/src/builtin/init/state.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/singletons.rs
  vm/actor/tests/account_actor_test.rs
  vm/actor/tests/balance_table_test.rs
  vm/actor/tests/cron_actor_test.rs
  vm/actor/tests/multimap_test.rs
  vm/actor/tests/set_multimap_test.rs
  vm/address/src/errors.rs
  vm/address/src/lib.rs
  vm/address/src/payload.rs
  vm/address/src/protocol.rs
  vm/address/tests/address_test.rs
  vm/default_runtime/src/gas_syscalls.rs
  vm/default_runtime/src/lib.rs
  vm/default_runtime/tests/transfer_test.rs
  vm/interpreter/src/lib.rs
  vm/message/src/unsigned_message.rs
  vm/message/tests/builder_test.rs
  vm/state_tree/src/lib.rs
  vm/state_tree/tests/state_tree_tests.rs
  vm/tests/params_test.rs
Labels: Status: Needs Review, VM

#385 BlockHeader Update
  Cargo.toml
  blockchain/beacon/Cargo.toml
  blockchain/beacon/src/beacon_entries.rs
  blockchain/beacon/src/lib.rs
  blockchain/blocks/Cargo.toml
  blockchain/blocks/src/header.rs
  ipld/car/tests/car_file_test.rs
  ipld/car/tests/devnet.car
  tests/serialization_tests/tests/block_header_ser.rs
Labels: Blockchain, Status: Needs Review

#386 Implements verify consensus fault syscall and reorg vm crates
  Cargo.toml
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/default_runtime/Cargo.toml
  vm/interpreter/Cargo.toml
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/default_syscalls.rs
  vm/interpreter/src/gas_block_store.rs
  vm/interpreter/src/gas_syscalls.rs
  vm/interpreter/src/lib.rs
  vm/interpreter/src/vm.rs
  vm/interpreter/tests/transfer_test.rs
  vm/runtime/Cargo.toml
  vm/runtime/src/lib.rs
Labels: Status: Needs Review, VM
