Repository ChainSafe/forest, pull requests merged in 2020-03, with the labels that each got.

#246 Refactor RPC and implement hello protocol
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/sync.rs
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/blocksync/message.rs
  node/forest_libp2p/src/blocksync/mod.rs
  node/forest_libp2p/src/hello/message.rs
  node/forest_libp2p/src/hello/mod.rs
  node/forest_libp2p/src/lib.rs
  node/forest_libp2p/src/rpc/codec.rs
  node/forest_libp2p/src/rpc/error.rs
  node/forest_libp2p/src/rpc/handler.rs
  node/forest_libp2p/src/rpc/mod.rs
  node/forest_libp2p/src/rpc/protocol.rs
  node/forest_libp2p/src/rpc/rpc_message.rs
  node/forest_libp2p/src/service.rs
  node/forest_libp2p/tests/blocksync_test.rs
  node/forest_libp2p/tests/decode_test.rs
  node/forest_libp2p/tests/hello_test.rs
  node/forest_libp2p/tests/rpc_test.rs
  node/forest_libp2p/tests/rpc_test_utils.rs
Labels: Network, Node, Status: Needs Review

#244 Connected blocksync requests and network polling thread
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/lib.rs
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/network_handler.rs
  blockchain/chain_sync/src/sync.rs
  forest/src/main.rs
  ipld/cid/src/lib.rs
Labels: Blockchain, Network, Status: Needs Review

#248 Implement sync fork
  blockchain/blocks/src/header.rs
  blockchain/blocks/src/tipset.rs
  blockchain/chain/src/store/tip_index.rs
  blockchain/chain_sync/src/sync.rs
  node/clock/src/lib.rs
Labels: Blockchain, Status: Needs Review

#252 Implement basic peer manager
  .gitignore
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/lib.rs
  blockchain/chain_sync/src/network_handler.rs
  blockchain/chain_sync/src/peer_manager.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/chain_sync/tests/syncer_test.rs
  blockchain/state_manager/src/lib.rs
  forest/src/cli/config.rs
  forest/src/main.rs
  node/forest_libp2p/src/hello/message.rs
  node/forest_libp2p/src/rpc/handler.rs
  node/forest_libp2p/src/service.rs
  vm/interpreter/src/lib.rs
Labels: Blockchain, Network, Status: Needs Review

#253 Update multihash dependency and Blockstore interface
  blockchain/blocks/src/header.rs
  blockchain/blocks/src/tipset.rs
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/tip_index.rs
  blockchain/chain_sync/src/bucket.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/tests/manager_test.rs
  encoding/src/cbor.rs
  ipld/amt/src/amt.rs
  ipld/amt/src/node.rs
  ipld/blockstore/src/lib.rs
  ipld/cid/Cargo.toml
  ipld/cid/src/lib.rs
  ipld/cid/src/to_cid.rs
  ipld/cid/tests/base_cid_tests.rs
  ipld/cid/tests/serde_tests.rs
  ipld/tests/ipld_test.rs
Labels: IPLD, Status: Needs Review

#254 Read CAR Files
  Cargo.toml
  ipld/car/Cargo.toml
  ipld/car/src/error.rs
  ipld/car/src/lib.rs
  ipld/car/src/util.rs
  ipld/car/tests/car_file_test.rs
  ipld/car/tests/devnet.car
  ipld/cid/src/lib.rs
Labels: IPLD, Status: Needs Changes

#256 Update runtime to new spec/ impl
  Cargo.toml
  crypto/src/lib.rs
  crypto/src/randomness.rs
  vm/abi/Cargo.toml
  vm/abi/src/lib.rs
  vm/abi/src/piece.rs
  vm/abi/src/sector.rs
  vm/actor/src/builtin/account.rs
  vm/actor/src/builtin/cron.rs
  vm/actor/src/builtin/init.rs
  vm/actor/src/builtin/reward.rs
  vm/actor/src/builtin/storage_power.rs
  vm/runtime/Cargo.toml
  vm/runtime/src/actor_code.rs
  vm/runtime/src/lib.rs
  vm/src/invoc.rs
Labels: Status: Needs Review, VM

#255 Hamt implementation
  Cargo.toml
  Makefile
  encoding/src/lib.rs
  ipld/hamt/Cargo.toml
  ipld/hamt/src/bitfield.rs
  ipld/hamt/src/error.rs
  ipld/hamt/src/hamt.rs
  ipld/hamt/src/hash.rs
  ipld/hamt/src/hash_bits.rs
  ipld/hamt/src/lib.rs
  ipld/hamt/src/node.rs
  ipld/hamt/src/pointer.rs
  ipld/hamt/tests/hamt_tests.rs
  node/db/src/memory.rs
Labels: IPLD, Status: Needs Review

#270 Update exit codes
  vm/actor/src/builtin/account.rs
  vm/actor/src/builtin/cron.rs
  vm/actor/src/builtin/init.rs
  vm/actor/src/builtin/reward.rs
  vm/actor/src/builtin/storage_power.rs
  vm/src/exit_code.rs
Labels: Status: Needs Review, VM

#271 Move CodeID and ActorState to vm crate
  vm/Cargo.toml
  vm/actor/src/builtin/init.rs
  vm/actor/src/lib.rs
  vm/runtime/Cargo.toml
  vm/src/actor_state.rs
  vm/src/code.rs
  vm/src/lib.rs
  vm/state_tree/Cargo.toml
  vm/state_tree/src/lib.rs
Labels: Status: Needs Review, VM

#273 State tree full implementation and refactor IPLD
  Makefile
  blockchain/blocks/src/header.rs
  blockchain/blocks/src/tipset.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  ipld/hamt/Cargo.toml
  ipld/hamt/src/error.rs
  ipld/hamt/src/hamt.rs
  ipld/hamt/src/lib.rs
  ipld/hamt/src/node.rs
  ipld/hamt/src/pointer.rs
  ipld/hamt/tests/hamt_tests.rs
  ipld/src/de.rs
  ipld/src/error.rs
  ipld/src/lib.rs
  ipld/src/ser.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/init.rs
  vm/actor/src/lib.rs
  vm/actor/src/singletons.rs
  vm/interpreter/src/lib.rs
  vm/runtime/Cargo.toml
  vm/src/actor_state.rs
  vm/src/lib.rs
  vm/src/state_tree.rs
  vm/state_tree/Cargo.toml
  vm/state_tree/src/lib.rs
  vm/state_tree/tests/state_tree_tests.rs
Labels: IPLD, Status: Needs Review, VM

#274 Remove unnecessary db trait
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  ipld/blockstore/src/lib.rs
  node/db/src/errors.rs
  node/db/src/lib.rs
  node/db/src/memory.rs
  node/db/src/rocks.rs
  node/db/tests/subtests/mod.rs
Labels: Node, Status: Needs Review

#279 Clean actors and update to spec
  blockchain/state_manager/src/lib.rs
  vm/actor/src/builtin/account.rs
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/account/state.rs
  vm/actor/src/builtin/cron.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/cron/state.rs
  vm/actor/src/builtin/init.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/init/state.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/builtin/reward.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/reward/state.rs
  vm/actor/src/builtin/storage_power.rs
  vm/actor/src/lib.rs
  vm/message/src/message_receipt.rs
  vm/runtime/src/actor_code.rs
  vm/runtime/src/lib.rs
  vm/src/method.rs
  vm/state_tree/src/lib.rs
  vm/state_tree/tests/state_tree_tests.rs
Labels: Status: Needs Review, VM

#282 Init actor implementation
  ipld/hamt/src/error.rs
  ipld/src/lib.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/codes.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/init/params.rs
  vm/actor/src/builtin/init/state.rs
  vm/actor/src/builtin/mod.rs
  vm/actor/src/builtin/singletons.rs
  vm/actor/src/lib.rs
  vm/address/src/lib.rs
  vm/runtime/src/lib.rs
  vm/state_tree/src/lib.rs
  vm/state_tree/tests/state_tree_tests.rs
Labels: Status: Needs Review, VM

#283 Move abi types and implement piece size
  Cargo.toml
  vm/Cargo.toml
  vm/abi/Cargo.toml
  vm/abi/src/lib.rs
  vm/abi/src/piece.rs
  vm/runtime/Cargo.toml
  vm/runtime/src/lib.rs
  vm/src/lib.rs
  vm/src/piece.rs
  vm/src/sector.rs
Labels: Status: Needs Review, VM

#281 Cron actor implementation
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/cron/state.rs
Labels: Status: Needs Review, VM

#284 Multisig actor implementation
  node/clock/src/lib.rs
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/account/state.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/multisig/state.rs
  vm/actor/src/builtin/multisig/types.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/runtime/src/lib.rs
Labels: Status: Needs Review, VM

#285 Implement balance table
  ipld/hamt/src/hamt.rs
  ipld/hamt/src/node.rs
  ipld/src/lib.rs
  node/clock/src/lib.rs
  node/db/src/errors.rs
  vm/actor/Cargo.toml
  vm/actor/src/lib.rs
  vm/actor/src/util/balance_table.rs
  vm/actor/src/util/mod.rs
  vm/actor/tests/balance_table_test.rs
  vm/src/token.rs
Labels: Status: Needs Review, VM

#288 feat(vm): implement system-actor
  vm/actor/src/builtin/mod.rs
  vm/actor/src/builtin/system/mod.rs
Labels: VM

#289 feat(vm): implement improved error handling
  vm/Cargo.toml
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/system/mod.rs
  vm/runtime/src/actor_code.rs
  vm/runtime/src/lib.rs
  vm/src/error.rs
  vm/src/lib.rs
Labels: Status: Needs Review, VM

#290 Implement multimap
  blockchain/chain_sync/src/errors.rs
  blockchain/chain_sync/src/sync.rs
  ipld/amt/src/amt.rs
  ipld/amt/src/error.rs
  ipld/amt/src/lib.rs
  ipld/amt/src/node.rs
  ipld/amt/tests/amt_tests.rs
  ipld/blockstore/src/lib.rs
  ipld/hamt/src/hamt.rs
  vm/actor/Cargo.toml
  vm/actor/src/util/balance_table.rs
  vm/actor/src/util/mod.rs
  vm/actor/src/util/multimap.rs
  vm/actor/tests/balance_table_test.rs
  vm/actor/tests/multimap_test.rs
Labels: Status: Needs Review, VM

#294 Sector types
  node/clock/src/lib.rs
  vm/Cargo.toml
  vm/actor/Cargo.toml
  vm/actor/src/lib.rs
  vm/runtime/src/lib.rs
  vm/src/actor_state.rs
  vm/src/deal_id.rs
  vm/src/lib.rs
  vm/src/piece.rs
  vm/src/randomness.rs
  vm/src/sector.rs
  vm/src/sector/mod.rs
  vm/src/sector/post.rs
  vm/src/sector/registered_proof.rs
  vm/src/sector/seal.rs
  vm/src/sector/serde.rs
Labels: Status: Merge Ready, VM

#295 Refactor annotated serializations
  blockchain/blocks/src/header.rs
  math/bigint/src/bigint_ser.rs
  math/bigint/src/biguint_ser.rs
  node/forest_libp2p/src/hello/message.rs
  vm/message/src/unsigned_message.rs
  vm/src/actor_state.rs
  vm/src/token.rs
Labels: Status: Needs Review, encoding

#297 Improve actors serialization handling
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/system/mod.rs
  vm/actor/src/lib.rs
  vm/src/error.rs
  vm/src/method.rs
Labels: Status: Needs Review, VM

#292 SetMultimap implementation
  vm/actor/src/lib.rs
  vm/actor/src/util/mod.rs
  vm/actor/src/util/set.rs
  vm/actor/src/util/set_multimap.rs
  vm/actor/tests/set_multimap_test.rs
  vm/actor/tests/set_test.rs
Labels: Status: Needs Review, VM

#296 Bitfield/ rle+ impl
  Cargo.toml
  Makefile
  utils/rleplus/Cargo.toml
  utils/rleplus/src/bitvec_serde.rs
  utils/rleplus/src/lib.rs
Labels: Status: Needs Review, VM

#299 Payment channel actor
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/sync.rs
  node/clock/src/lib.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/paych/state.rs
  vm/actor/src/builtin/paych/types.rs
  vm/message/src/lib.rs
  vm/message/src/signed_message.rs
  vm/message/src/unsigned_message.rs
  vm/message/tests/builder_test.rs
  vm/runtime/src/lib.rs
  vm/src/actor_state.rs
  vm/src/method.rs
  vm/src/token.rs
  vm/state_tree/tests/state_tree_tests.rs
Labels: Status: Needs Review, VM

#309 Change ChainEpoch and TokenAmount types
  blockchain/blocks/src/header.rs
  blockchain/blocks/src/tipset.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  math/bigint/src/bigint_ser.rs
  math/bigint/src/biguint_ser.rs
  node/clock/src/lib.rs
  node/forest_libp2p/tests/decode_test.rs
  node/forest_libp2p/tests/hello_test.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/multisig/state.rs
  vm/actor/src/builtin/multisig/types.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/paych/state.rs
  vm/actor/src/builtin/paych/types.rs
  vm/actor/src/builtin/reward/state.rs
  vm/actor/src/util/balance_table.rs
  vm/actor/tests/balance_table_test.rs
  vm/message/src/unsigned_message.rs
  vm/message/tests/builder_test.rs
  vm/src/actor_state.rs
  vm/src/token.rs
Labels: Status: Needs Review

#317 Switch MethodNum and ActorID to aliases
  tests/serialization_tests/tests/u_message_ser.rs
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/init/state.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/singletons.rs
  vm/actor/src/builtin/system/mod.rs
  vm/actor/src/lib.rs
  vm/src/actor_state.rs
  vm/src/method.rs
  vm/tests/params_test.rs
Labels: Status: Needs Review, VM

#308 Storage Power actor
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/init/params.rs
  vm/actor/src/builtin/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/power/policy.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/builtin/power/types.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/reward/types.rs
  vm/actor/src/builtin/shared.rs
  vm/actor/src/builtin/system/mod.rs
  vm/actor/src/lib.rs
  vm/actor/src/util/balance_table.rs
  vm/runtime/src/lib.rs
  vm/src/error.rs
  vm/src/sector/mod.rs
Labels: Status: Needs Review, VM
