Repository ChainSafe/forest, pull requests merged in 2020-06, with the labels that each got.

#441 Add CircleCI
  .circleci/config.yml
Labels: Status: Needs Review, Type: Maintenance

#466 Implement compatible bitfield
  Cargo.toml
  Makefile
  utils/bitfield/Cargo.toml
  utils/bitfield/src/bitvec_serde.rs
  utils/bitfield/src/lib.rs
  utils/bitfield/src/rleplus.rs
  utils/bitfield/tests/bitfield_tests.rs
  utils/rleplus/src/bitvec_serde.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/miner/state.rs
Labels: Status: Needs Review, VM

#458 update power, reward and market actors, rt and registered proofs relative to miner actor
  blockchain/chain/src/store/chain_store.rs
  blockchain/state_manager/src/lib.rs
  types/src/sector/mod.rs
  types/src/sector/registered_proof.rs
  types/src/sector/seal.rs
  types/src/sector/serde_tests.rs
  vm/actor/src/builtin/market/deal.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/market/types.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/power/policy.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/builtin/power/types.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/reward/state.rs
  vm/actor/src/builtin/verifreg/types.rs
  vm/actor/src/lib.rs
  vm/actor/tests/common/mod.rs
  vm/interpreter/src/default_runtime.rs
  vm/runtime/src/lib.rs
Labels: Spec Change, Status: Needs Review, VM

#454 Ashanti/connect state transition
  blockchain/blocks/src/header/mod.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
Labels: Blockchain, Status: Needs Changes

#473 Ashanti/chain store channel
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/tip_index.rs
  blockchain/chain_sync/src/sync.rs
  forest/src/cli/genesis.rs
Labels: Blockchain, Status: Needs Review

#462 Tide JSONRPC over HTTP
  Cargo.toml
  Makefile
  blockchain/blocks/src/tipset.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/src/lib.rs
  forest/Cargo.toml
  forest/src/main.rs
  ipld/cid/Cargo.toml
  ipld/cid/src/json.rs
  node/rpc/Cargo.toml
  node/rpc/src/chain_api.rs
  node/rpc/src/lib.rs
  vm/message/Cargo.toml
  vm/message/src/signed_message.rs
  vm/message/src/unsigned_message.rs
Labels: Blockchain, RPC, Status: Needs Changes

#479 Updated Code to Pass Checks With Rust 1.44
  blockchain/beacon/src/lib.rs
  forest/src/main.rs
  ipld/graphsync/src/message/proto/mod.rs
Labels: Priority: 2 - High, Status: Needs Review, Type: Maintenance

#481 Switch bls pub key from using vec
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/src/lib.rs
  vm/address/src/lib.rs
Labels: Status: Needs Review

#483 Batch seal verification implementation
  vm/interpreter/src/gas_syscalls.rs
  vm/runtime/Cargo.toml
  vm/runtime/src/lib.rs
Labels: Status: Needs Review, VM

#478 Implements Storage Miner critical Chain API methods
  blockchain/blocks/src/header/json.rs
  blockchain/blocks/src/tipset.rs
  blockchain/chain/src/store/chain_store.rs
  node/rpc/Cargo.toml
  node/rpc/src/chain_api.rs
  node/rpc/src/lib.rs
Labels: RPC, Status: Merge Ready

#480 Update Reward actor to new spec
  types/src/sector/mod.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/mod.rs
  vm/actor/src/builtin/network.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/reward/state.rs
  vm/actor/src/builtin/reward/types.rs
  vm/actor/tests/reward_actor_test.rs
Labels: Spec Change, Status: Needs Review, VM

#484 Adds Json serialization for Message Receipts and ActorState
  vm/Cargo.toml
  vm/message/Cargo.toml
  vm/message/src/message_receipt.rs
  vm/src/actor_state.rs
Labels: Blockchain, RPC, Status: Needs Review

#494 implements request_miner_control_addrs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/shared.rs
Labels: Status: Needs Review, VM

#493 Ashanti/winning posts
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/utils.rs
  vm/runtime/src/lib.rs
Labels: Blockchain, Status: Needs Review

#500 Fix ecrecover and verify methods
  crypto/src/signature.rs
  key_management/Cargo.toml
  key_management/src/wallet.rs
  key_management/src/wallet_helpers.rs
  vm/interpreter/src/gas_tracker/price_list.rs
Labels: Crypto, Priority: 3 - Medium, Status: Needs Review, Type: Bug

#501 Implement Kademlia discovery
  README.md
  blockchain/chain_sync/src/sync.rs
  forest/src/logger/mod.rs
  forest/src/main.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/config.rs
  node/forest_libp2p/src/rpc/handler.rs
  node/forest_libp2p/src/rpc/protocol.rs
  node/forest_libp2p/src/service.rs
Labels: Network, Status: Needs Review

#507 Update proofs to v4
  blockchain/beacon/Cargo.toml
  blockchain/blocks/Cargo.toml
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/sync.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/utils.rs
  types/Cargo.toml
  types/src/sector/mod.rs
  types/src/sector/post.rs
  types/src/sector/registered_proof.rs
  types/src/sector/seal.rs
  types/src/sector/serde_tests.rs
  utils/bigint/Cargo.toml
  utils/commcid/Cargo.toml
  vm/actor/src/builtin/market/types.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/policy.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/miner/types.rs
  vm/actor/src/builtin/power/types.rs
  vm/actor/src/builtin/reward/types.rs
  vm/interpreter/src/gas_syscalls.rs
  vm/interpreter/src/gas_tracker/price_list.rs
  vm/runtime/Cargo.toml
  vm/runtime/src/lib.rs
  vm/runtime/tests/syscalls_test.rs
Labels: Spec Change, Status: Needs Review

#509 Update bootnodes and genesis for testnet
  forest/src/cli/devnet.car
  node/forest_libp2p/src/config.rs
Labels: Status: Needs Review, Type: Maintenance

#511 A bare-bones GraphSync ResponseManager
  ipld/graphsync/Cargo.toml
  ipld/graphsync/src/lib.rs
  ipld/graphsync/src/message/mod.rs
  ipld/graphsync/src/response_manager/mod.rs
  ipld/graphsync/src/response_manager/response_builder.rs
  ipld/src/selector/walk.rs
  ipld/tests/walk_tests.rs
Labels: GraphSync, Status: Needs Review

#517 Remove dead code and update CI
  .circleci/config.yml
  .github/workflows/ci-rust.yml
  Cargo.lock
  Cargo.toml
  Makefile
  blockchain/Cargo.toml
  blockchain/blocks/src/tipset.rs
  blockchain/src/lib.rs
  blockchain/src/main.rs
  blockchain/src/message_pool/mod.rs
  blockchain/src/message_pool/pool.rs
  blockchain/src/storage_consensus/mod.rs
  node/Cargo.toml
  node/src/lib.rs
Labels: Status: Needs Review, Type: Maintenance

#519 Update default branch name to main
  .circleci/config.yml
  .github/workflows/ci-rust.yml
  README.md
Labels: Status: Needs Review, Type: Maintenance

#520 Fix docs publish rule
  .github/workflows/ci-rust.yml
Labels: Status: Needs Review

#426 Rupan/market actor tests
  utils/test_utils/src/chain_structures.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/market/policy.rs
  vm/actor/src/builtin/market/state.rs
  vm/actor/src/util/optional_epoch.rs
  vm/actor/tests/common/mod.rs
  vm/actor/tests/market_actor_test.rs
Labels: Status: Needs Changes, VM

#506 Bitfield improvements
  Cargo.lock
  blockchain/state_manager/src/utils.rs
  utils/bitfield/Cargo.toml
  utils/bitfield/src/bitvec_serde.rs
  utils/bitfield/src/iter.rs
  utils/bitfield/src/lib.rs
  utils/bitfield/src/rleplus.rs
  utils/bitfield/src/rleplus/iter.rs
  utils/bitfield/src/rleplus/mod.rs
  utils/bitfield/src/rleplus/reader.rs
  utils/bitfield/src/rleplus/writer.rs
  utils/bitfield/tests/bitfield_tests.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/miner/deadlines.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/state.rs
Labels: Status: Needs Review

#523 Update proofs-api to 4.0.1
  Cargo.lock
  blockchain/chain_sync/Cargo.toml
  blockchain/state_manager/Cargo.toml
  crypto/Cargo.toml
  crypto/src/signature.rs
  types/Cargo.toml
  utils/commcid/Cargo.toml
  vm/runtime/Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#516 Refactor CLI and implement fetch-params
  Cargo.lock
  forest/Cargo.toml
  forest/src/cli/mod.rs
  forest/src/daemon.rs
  forest/src/logger/mod.rs
  forest/src/main.rs
  forest/src/paramfetch/mod.rs
  forest/src/paramfetch/parameters.json
  forest/src/subcommand.rs
Labels: CLI, Status: Needs Review

#524 Implementing Market Balance
  blockchain/state_manager/src/lib.rs
Labels: Status: Needs Review

#526 Update async-std runtime setup
  blockchain/beacon/src/drand_api/api.rs
  blockchain/beacon/src/drand_api/common.rs
  forest/src/cli/mod.rs
  forest/src/daemon.rs
  forest/src/main.rs
  forest/src/subcommand.rs
Labels: Status: Needs Review

#525 Remove bitvec dependency and other bit field changes
  Cargo.lock
  utils/bitfield/Cargo.toml
  utils/bitfield/src/iter.rs
  utils/bitfield/src/lib.rs
  utils/bitfield/src/rleplus/mod.rs
  utils/bitfield/src/rleplus/reader.rs
  utils/bitfield/src/rleplus/writer.rs
  utils/bitfield/tests/bitfield_tests.rs
Labels: Status: Merge Ready
