Repository ChainSafe/forest, pull requests merged in 2020-09, with the labels that each got.

#675 Remove TODOs from scoping
  Cargo.lock
  crypto/src/vrf.rs
  forest/src/daemon.rs
  ipld/car/src/util.rs
  ipld/cid/src/lib.rs
  node/forest_libp2p/src/behaviour.rs
  types/src/sector/post.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/market/deal.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/util/balance_table.rs
  vm/address/src/lib.rs
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/gas_syscalls.rs
Labels: Status: Needs Review, Type: Maintenance

#678 Update apply_blocks call
  .gitignore
  Cargo.lock
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/cron/state.rs
  vm/interpreter/src/vm.rs
  vm/runtime/Cargo.toml
Labels: Status: Needs Review, VM

#683 Fix bitswap breaking patch release
  Cargo.lock
  node/forest_libp2p/Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#685 Swap secio authentication for noise
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/service.rs
Labels: Network, Spec Change, Status: Needs Review

#686 Update blocksync message formats
  .github/workflows/ci-rust.yml
  Cargo.lock
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/sync.rs
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/blocksync/message.rs
  node/forest_libp2p/src/service.rs
  node/forest_libp2p/tests/decode_test.rs
  utils/test_utils/src/chain_structures.rs
Labels: Spec Change, Status: Needs Review

#668 Update statetree cache
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/message_pool/src/msgpool.rs
  blockchain/state_manager/src/lib.rs
  node/rpc/src/wallet_api.rs
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/vm.rs
  vm/state_tree/src/lib.rs
  vm/state_tree/tests/state_tree_tests.rs
Labels: Status: Merge Ready, VM

#688 Fix docs publish workflow
  .github/workflows/ci-rust.yml
Labels: Status: Needs Review, Type: Maintenance

#503 Chain syncing verification fixes
  blockchain/blocks/src/header/mod.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/network_handler.rs
  blockchain/chain_sync/src/sync.rs
  crypto/src/signature.rs
  node/forest_libp2p/src/blocksync/message.rs
  node/forest_libp2p/src/service.rs
Labels: Blockchain, Status: Needs Review

#644 Add CLI command to add Genesis Miner to Genesis Template
  .gitignore
  Cargo.lock
  forest/Cargo.toml
  forest/src/cli/genesis_cmd.rs
  types/Cargo.toml
  types/src/genesis/mod.rs
  utils/bigint/Cargo.toml
  utils/bigint/src/bigint_ser.rs
  vm/address/src/errors.rs
  vm/address/src/lib.rs
Labels: CLI, Status: Merge Ready

#695 Print out conformance results and add log for skips
  Makefile
  tests/conformance_tests/tests/conformance_runner.rs
Labels: Status: Needs Review, Type: Maintenance

#697 Drand ignore env variable
  blockchain/beacon/src/drand.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  forest/src/cli/mod.rs
Labels: Drand, Status: Needs Review

#694 Fix StateManager use in different components
  Cargo.lock
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/message_pool/Cargo.toml
  blockchain/message_pool/src/msgpool.rs
  forest/src/daemon.rs
  node/rpc/src/lib.rs
  node/rpc/src/sync_api.rs
Labels: Blockchain, Status: Needs Review

#693 ChainSync refactor
  Cargo.lock
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/tip_index.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/bucket.rs
  blockchain/chain_sync/src/lib.rs
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/network_handler.rs
  blockchain/chain_sync/src/peer_manager.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/chain_sync/src/sync_state.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/message_pool/Cargo.toml
  blockchain/message_pool/src/msgpool.rs
  forest/src/cli/genesis.rs
  forest/src/daemon.rs
  ipld/graphsync/src/message/mod.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/service.rs
  node/rpc/src/lib.rs
  node/rpc/src/sync_api.rs
  utils/test_utils/src/chain_structures.rs
  vm/message/src/unsigned_message.rs
Labels: Blockchain, Network, Status: Merge Ready

#703 Semantic Validation for Messages
  Cargo.lock
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/base_fee.rs
  node/rpc/src/gas_api.rs
  types/src/lib.rs
  vm/message/Cargo.toml
  vm/message/src/chain_message.rs
  vm/message/src/lib.rs
  vm/message/src/signed_message.rs
  vm/message/src/unsigned_message.rs
Labels: Blockchain, Status: Needs Review

#701 Peer stats tracking and selection
  Cargo.lock
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/peer_manager.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/chain_sync/src/sync_worker.rs
  node/forest_libp2p/src/blocksync/message.rs
Labels: Blockchain, Network, Status: Needs Review

#702 Make block validations async
  blockchain/blocks/src/header/mod.rs
  blockchain/chain_sync/src/sync_worker.rs
Labels: Status: Needs Review, Type: Enhancement

#714 Update AMT max index bound
  ipld/amt/src/amt.rs
  ipld/amt/src/error.rs
  ipld/amt/src/lib.rs
  ipld/amt/src/node.rs
  ipld/amt/src/root.rs
  ipld/amt/tests/amt_tests.rs
Labels: Spec Change, Status: Needs Review

#711 Update block validations
  Cargo.lock
  blockchain/blocks/Cargo.toml
  blockchain/blocks/src/election_proof.rs
  blockchain/blocks/src/header/json.rs
  blockchain/blocks/src/header/mod.rs
  blockchain/blocks/src/lib.rs
  blockchain/blocks/src/ticket.rs
  blockchain/blocks/src/tipset.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/errors.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/message_pool/src/msgpool.rs
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/utils.rs
  crypto/src/election_proof.rs
  crypto/src/lib.rs
  crypto/src/signature.rs
  crypto/src/vrf.rs
  node/clock/src/lib.rs
  node/rpc/src/chain_api.rs
  node/rpc/src/gas_api.rs
  node/rpc/src/mpool_api.rs
  node/rpc/src/state_api.rs
  node/rpc/src/wallet_api.rs
  types/src/lib.rs
  utils/test_utils/src/chain_structures.rs
  vm/actor/src/builtin/network.rs
  vm/actor/src/builtin/power/state.rs
Labels: Blockchain, Status: Needs Review

#715 Adding More Reward Actor Tests
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/tests/common/mod.rs
  vm/actor/tests/reward_actor_test.rs
Labels: Status: Needs Review, VM

#670 Storage miner integration
  Cargo.lock
  blockchain/beacon/Cargo.toml
  blockchain/blocks/src/tipset.rs
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/sync.rs
  blockchain/message_pool/Cargo.toml
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  forest/Cargo.toml
  forest/src/cli/genesis.rs
  forest/src/daemon.rs
  ipld/Cargo.toml
  ipld/graphsync/Cargo.toml
  node/forest_libp2p/Cargo.toml
  node/rpc/Cargo.toml
  node/rpc/src/chain_api.rs
  node/rpc/src/lib.rs
  node/rpc/src/state_api.rs
  node/rpc/src/sync_api.rs
  utils/test_utils/Cargo.toml
  vm/address/src/lib.rs
  vm/message/src/message_receipt.rs
Labels: RPC, Status: Needs Changes, Storage Miner

#691 Update Miner actor
  Cargo.lock
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/utils.rs
  encoding/src/bytes.rs
  ipld/amt/src/amt.rs
  ipld/amt/src/node.rs
  node/rpc/src/state_api.rs
  types/Cargo.toml
  types/src/sector/mod.rs
  types/src/sector/registered_proof.rs
  types/src/sector/seal.rs
  vm/actor/src/builtin/market/types.rs
  vm/actor/src/builtin/miner/bitfield_queue.rs
  vm/actor/src/builtin/miner/deadline_assignment.rs
  vm/actor/src/builtin/miner/deadline_state.rs
  vm/actor/src/builtin/miner/deadlines.rs
  vm/actor/src/builtin/miner/expiration_queue.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/monies.rs
  vm/actor/src/builtin/miner/partition_state.rs
  vm/actor/src/builtin/miner/policy.rs
  vm/actor/src/builtin/miner/quantize.rs
  vm/actor/src/builtin/miner/sector_map.rs
  vm/actor/src/builtin/miner/sectors.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/miner/termination.rs
  vm/actor/src/builtin/miner/types.rs
  vm/actor/src/builtin/miner/vesting_state.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/power/types.rs
  vm/actor/tests/deadline_test.rs
  vm/actor/tests/market_actor_test.rs
  vm/interpreter/src/default_syscalls.rs
  vm/src/error.rs
Labels: Status: Needs Review, VM

#705 Mempool Update
  Cargo.lock
  blockchain/message_pool/Cargo.toml
  blockchain/message_pool/src/config.rs
  blockchain/message_pool/src/errors.rs
  blockchain/message_pool/src/lib.rs
  blockchain/message_pool/src/msgpool.rs
  forest/src/daemon.rs
  node/rpc/src/sync_api.rs
  vm/interpreter/src/lib.rs
Labels: Blockchain, Status: Needs Review
