Repository ChainSafe/forest, pull requests merged in 2020-08, with the labels that each got.

#599 Returns an Error in case of slicing non-ascii strings
  vm/address/src/lib.rs
Labels: Status: Needs Review

#597 Remove incorrectly ported sanity check from go implementation
  vm/interpreter/src/vm.rs
Labels: Status: Merge Ready

#598 Add address bugfix tests and bump crate version
  Cargo.lock
  vm/address/Cargo.toml
  vm/address/tests/address_test.rs
Labels: Status: Needs Review, VM

#593 Market actor update
  Cargo.lock
  ipld/cid/src/codec.rs
  ipld/hamt/src/hamt.rs
  types/src/sector/mod.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/market/deal.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/market/policy.rs
  vm/actor/src/builtin/market/state.rs
  vm/actor/src/builtin/market/types.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/miner/types.rs
  vm/actor/src/builtin/network.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/power/policy.rs
  vm/actor/src/builtin/power/types.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/reward/state.rs
  vm/actor/src/builtin/reward/types.rs
  vm/actor/src/lib.rs
  vm/actor/src/util/set_multimap.rs
  vm/actor/tests/market_actor_test.rs
Labels: Status: Merge Ready, VM

#606 Multisig actor update
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/multisig/state.rs
  vm/actor/src/builtin/multisig/types.rs
Labels: Status: Merge Ready, VM

#594 Smoothing Functions For Actors
  vm/actor/src/builtin/mod.rs
  vm/actor/src/util/math.rs
  vm/actor/src/util/mod.rs
  vm/actor/src/util/smooth/alpha_beta_filter.rs
  vm/actor/src/util/smooth/mod.rs
  vm/actor/src/util/smooth/smooth_func.rs
  vm/actor/tests/alpha_beta_filter_test.rs
Labels: CryptoEcon, Status: Merge Ready

#608 Paych actor updates
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/paych/state.rs
  vm/actor/src/builtin/paych/types.rs
  vm/actor/tests/common/mod.rs
  vm/actor/tests/paych_actor_test.rs
Labels: Status: Merge Ready, VM

#611 Fix string decode handling network
  vm/address/Cargo.toml
  vm/address/src/lib.rs
  vm/address/tests/address_test.rs
Labels: Status: Needs Review, VM

#604 Add Persistent KeyStore
  Cargo.lock
  forest/src/daemon.rs
  key_management/Cargo.toml
  key_management/src/keystore.rs
  key_management/src/wallet.rs
  node/rpc/src/wallet_api.rs
Labels: Node, Status: Needs Review

#609 Update verified registry actor
  Cargo.lock
  utils/bigint/src/bigint_ser.rs
  vm/actor/src/builtin/verifreg/mod.rs
  vm/actor/src/builtin/verifreg/state.rs
  vm/actor/src/builtin/verifreg/types.rs
Labels: Status: Needs Review, VM

#619 Reward actor update
  vm/actor/src/builtin/market/state.rs
  vm/actor/src/builtin/reward/expneg.rs
  vm/actor/src/builtin/reward/logic.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/reward/state.rs
  vm/actor/src/builtin/reward/types.rs
  vm/actor/src/util/smooth/alpha_beta_filter.rs
  vm/actor/src/util/smooth/smooth_func.rs
  vm/actor/tests/reward_actor_test.rs
  vm/interpreter/src/vm.rs
Labels: Status: Merge Ready, VM

#625 Fix bug in reading and persisting keystore data
  forest/src/daemon.rs
  key_management/src/errors.rs
  key_management/src/keystore.rs
  node/forest_libp2p/src/service.rs
Labels: Status: Needs Review, Type: Bug

#612 New Genesis Template cli command
  Cargo.lock
  forest/Cargo.toml
  forest/src/cli/genesis_cmd.rs
  forest/src/cli/mod.rs
  forest/src/subcommand.rs
  types/Cargo.toml
  types/src/genesis/mod.rs
  types/src/lib.rs
Labels: CLI, Node

#622 Update system actor
  vm/actor/src/builtin/system/mod.rs
Labels: Status: Merge Ready, VM

#617 Add Bitfield cut operator and other improvements
  utils/bitfield/benches/benchmarks/main.rs
  utils/bitfield/src/iter.rs
  utils/bitfield/src/iter/combine.rs
  utils/bitfield/src/iter/mod.rs
  utils/bitfield/src/lib.rs
  utils/bitfield/tests/bitfield_tests.rs
Labels: Status: Needs Review, VM

#618 Rpc state implementation
  Cargo.lock
  Cargo.toml
  blockchain/blocks/src/tipset.rs
  blockchain/state_manager/src/lib.rs
  forest/src/daemon.rs
  node/rpc/Cargo.toml
  node/rpc/src/chain_api.rs
  node/rpc/src/lib.rs
  node/rpc/src/mpool_api.rs
  node/rpc/src/state_api.rs
  node/rpc/src/sync_api.rs
  node/rpc/src/wallet_api.rs
  node/state_api/Cargo.toml
  node/state_api/src/lib.rs
  types/Cargo.toml
  utils/bitfield/Cargo.toml
  utils/bitfield/src/lib.rs
  utils/bitfield/src/rleplus/writer.rs
  vm/actor/src/builtin/miner/deadlines.rs
  vm/address/Cargo.toml
  vm/address/src/lib.rs
  vm/message/src/chain_message.rs
  vm/message/src/message_receipt.rs
  vm/message/src/unsigned_message.rs
Labels: RPC, Status: Needs Changes

#623 Update to new empty amt serialization
  blockchain/chain_sync/src/sync.rs
  crypto/src/vrf.rs
  ipld/amt/src/bitmap.rs
  ipld/tests/walk_tests.rs
  utils/bigint/src/bigint_ser.rs
  utils/bigint/src/biguint_ser.rs
  utils/bitfield/src/rleplus/mod.rs
  vm/address/src/lib.rs
Labels: IPLD, Status: Needs Review

#624 Update default hamt hash function to sha256 and make algo generic
  Cargo.lock
  blockchain/state_manager/src/utils.rs
  ipld/hamt/Cargo.toml
  ipld/hamt/src/bitfield.rs
  ipld/hamt/src/hamt.rs
  ipld/hamt/src/hash_algorithm.rs
  ipld/hamt/src/hash_bits.rs
  ipld/hamt/src/lib.rs
  ipld/hamt/src/node.rs
  ipld/hamt/src/pointer.rs
  ipld/hamt/tests/hamt_tests.rs
  types/src/lib.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/lib.rs
  vm/actor/src/util/balance_table.rs
  vm/actor/src/util/multimap.rs
  vm/actor/src/util/set.rs
  vm/actor/src/util/set_multimap.rs
  vm/interpreter/tests/transfer_test.rs
  vm/state_tree/Cargo.toml
  vm/state_tree/src/lib.rs
  vm/state_tree/tests/state_tree_tests.rs
Labels: IPLD, Spec Change, Status: Needs Review

#601 Update commcid to new codes and validation
  ipld/blockstore/src/buffered.rs
  utils/commcid/src/lib.rs
  utils/commcid/tests/commcid_tests.rs
  vm/runtime/src/lib.rs
  vm/runtime/tests/syscalls_test.rs
Labels: Spec Change, Status: Needs Review

#637 Separate ticket and beacon randomness
  Cargo.lock
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  node/rpc/src/chain_api.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/tests/common/mod.rs
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/rand.rs
  vm/runtime/src/lib.rs
Labels: Drand, Spec Change, Status: Merge Ready

#641 Update libp2p, proofs, and other deps
  Cargo.lock
  blockchain/chain_sync/Cargo.toml
  blockchain/message_pool/Cargo.toml
  blockchain/state_manager/Cargo.toml
  forest/Cargo.toml
  ipld/car/Cargo.toml
  ipld/graphsync/Cargo.toml
  ipld/graphsync/src/message/proto/message.rs
  node/db/Cargo.toml
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/service.rs
  node/rpc-client/Cargo.toml
  types/Cargo.toml
  utils/bitfield/Cargo.toml
  utils/commcid/Cargo.toml
  vm/actor/Cargo.toml
  vm/runtime/Cargo.toml
  vm/state_tree/Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#643 Builtin actors 0.9.3 update
  crypto/src/randomness.rs
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/init/state.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/market/state.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/multisig/types.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/paych/state.rs
  vm/actor/src/builtin/paych/types.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/power/types.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/shared.rs
  vm/actor/src/builtin/system/mod.rs
  vm/actor/src/builtin/verifreg/mod.rs
  vm/actor/tests/paych_actor_test.rs
  vm/message/src/unsigned_message.rs
Labels: Status: Needs Review, VM

#627 Adding Puppet Actor
  vm/actor/src/builtin/codes.rs
  vm/actor/src/builtin/mod.rs
  vm/actor/src/builtin/puppet/mod.rs
  vm/actor/src/builtin/puppet/state.rs
  vm/actor/src/builtin/singletons.rs
  vm/actor/tests/common/mod.rs
  vm/actor/tests/puppet_actor_test.rs
Labels: Status: Merge Ready, VM

#649 Update gas charges in VM
  Cargo.lock
  vm/actor/src/builtin/power/mod.rs
  vm/actor/tests/common/mod.rs
  vm/interpreter/Cargo.toml
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/gas_block_store.rs
  vm/interpreter/src/gas_syscalls.rs
  vm/interpreter/src/gas_tracker/gas_charge.rs
  vm/interpreter/src/gas_tracker/mod.rs
  vm/interpreter/src/gas_tracker/price_list.rs
  vm/interpreter/src/lib.rs
  vm/interpreter/src/vm.rs
  vm/interpreter/tests/transfer_test.rs
  vm/runtime/src/lib.rs
Labels: Interop, VM

#651 Released updated protocol crates
  Cargo.lock
  blockchain/message_pool/Cargo.toml
  crypto/Cargo.toml
  encoding/Cargo.toml
  ipld/cid/Cargo.toml
  utils/bigint/Cargo.toml
  utils/json_utils/Cargo.toml
  vm/Cargo.toml
  vm/address/Cargo.toml
  vm/message/Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#650 Space race genesis and bootnodes updates
  Cargo.lock
  blockchain/beacon/src/drand.rs
  blockchain/beacon/tests/drand.rs
  forest/Cargo.toml
  forest/src/cli/config.rs
  forest/src/cli/devnet.car
  forest/src/daemon.rs
  ipld/car/src/lib.rs
  ipld/car/src/util.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/config.rs
Labels: Status: Needs Review, Type: Maintenance

#652 Fix actor creation and deletion logic
  vm/actor/src/builtin/codes.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/tests/common/mod.rs
  vm/interpreter/src/default_runtime.rs
  vm/runtime/src/lib.rs
  vm/src/code.rs
  vm/src/lib.rs
Labels: Status: Needs Review, Type: Bug, VM

#653 Adding Chaos Actor
  vm/actor/src/builtin/codes.rs
  vm/actor/src/builtin/mod.rs
  vm/actor/src/builtin/puppet/state.rs
  vm/actor/src/builtin/singletons.rs
  vm/actor/src/util/chaos/mod.rs
  vm/actor/src/util/chaos/state.rs
  vm/actor/src/util/chaos/types.rs
  vm/actor/src/util/mod.rs
  vm/actor/src/util/puppet/mod.rs
  vm/actor/src/util/puppet/state.rs
  vm/actor/src/util/unmarshallable.rs
  vm/actor/tests/puppet_actor_test.rs
Labels: Status: Needs Review, VM

#626 Add benchmarks and cleanup AMT
  Cargo.lock
  ipld/amt/Cargo.toml
  ipld/amt/benches/amt_benchmark.rs
  ipld/amt/src/node.rs
Labels: IPLD, Status: Merge Ready

#656 Fix inconsistencies in apply_message
  vm/interpreter/src/vm.rs
Labels: Status: Needs Review, Type: Bug, VM

#657 Fix bugs in vm and update runner
  tests/conformance_tests/tests/conformance_runner.rs
  vm/interpreter/src/vm.rs
Labels: Status: Needs Review, Type: Bug, VM

#658 Fix Get Actor
  vm/state_tree/src/lib.rs
Labels: Status: Needs Review, VM

#659 Fix internal send bug, remove message ref from runtime
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/vm.rs
  vm/runtime/src/lib.rs
Labels: Status: Needs Review, VM

#635 Make hamt value type generic and add benchmarks
  Cargo.lock
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/utils.rs
  ipld/hamt/Cargo.toml
  ipld/hamt/benches/hamt_benchmark.rs
  ipld/hamt/src/hamt.rs
  ipld/hamt/src/lib.rs
  ipld/hamt/src/node.rs
  ipld/hamt/src/pointer.rs
  ipld/hamt/tests/hamt_tests.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/init/state.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/market/state.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/builtin/verifreg/mod.rs
  vm/actor/src/lib.rs
  vm/actor/src/util/balance_table.rs
  vm/actor/src/util/multimap.rs
  vm/actor/src/util/set.rs
  vm/actor/src/util/set_multimap.rs
  vm/state_tree/Cargo.toml
  vm/state_tree/src/lib.rs
Labels: IPLD, Status: Needs Review

#660 Fix caller validation on nested sends
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/vm.rs
Labels: Status: Needs Review, VM

#661 add validation in chaos actor
  vm/actor/src/util/chaos/mod.rs
Labels: Status: Needs Review, VM

#662 check value correctly before transfer
  vm/interpreter/src/default_runtime.rs
Labels: Status: Needs Review, VM

#663 Handle failed retrieve of actor state
  vm/interpreter/src/vm.rs
Labels: Status: Needs Review, VM

#664 Fix runtime implementation to return gas blockstore
  vm/interpreter/src/default_runtime.rs
Labels: Status: Needs Review, VM

#665 fix serialization of TxnIdParams
  vm/actor/src/builtin/multisig/types.rs
Labels: Status: Needs Review, VM

#667 Update EPOCH_DURATION_SECONDS
  node/clock/src/lib.rs
  vm/actor/src/builtin/network.rs
Labels: Status: Needs Review, VM

#666 Update runtime transaction logic
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/verifreg/mod.rs
  vm/actor/src/util/puppet/mod.rs
  vm/actor/tests/common/mod.rs
  vm/interpreter/src/default_runtime.rs
  vm/runtime/src/lib.rs
Labels: Status: Needs Review, VM

#671 Update edge cases for dynamic error handling in VM
  tests/conformance_tests/tests/conformance_runner.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/interpreter/src/default_runtime.rs
  vm/src/error.rs
Labels: Status: Needs Review, VM

#647 Adding Mdns and Kad Toggle
  forest/src/cli/config.rs
  forest/src/cli/mod.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/config.rs
Labels: Status: Needs Review
