Repository ChainSafe/forest, pull requests merged in 2020-12, with the labels that each got.

#874 A bunch of fixes for the RPC
  blockchain/chain/src/store/chain_store.rs
  blockchain/message_pool/src/msgpool/selection.rs
  forest/src/daemon.rs
  node/rpc/src/gas_api.rs
  node/rpc/src/lib.rs
  node/rpc/src/mpool_api.rs
  node/rpc/src/state_api.rs
  node/rpc/src/sync_api.rs
  node/rpc/src/wallet_api.rs
  types/src/build_version/mod.rs
  types/src/deadlines/mod.rs
  vm/actor/src/builtin/miner/deadline_state.rs
  vm/message/src/signed_message.rs
  vm/message/src/unsigned_message.rs
Labels: RPC, Status: Needs Review, Storage Miner

#875 Form tipsets
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/mod.rs
  blockchain/chain/src/store/tipset_tracker.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/chain_sync/src/sync_worker/validate_block_test.rs
Labels: Blockchain, Status: Needs Review

#879 Release crates for actors v2 upgrade
  Cargo.lock
  Makefile
  blockchain/chain/Cargo.toml
  blockchain/chain_sync/Cargo.toml
  blockchain/message_pool/Cargo.toml
  blockchain/state_manager/Cargo.toml
  encoding/Cargo.toml
  forest/Cargo.toml
  ipld/Cargo.toml
  ipld/amt/Cargo.toml
  ipld/amt/fuzz/Cargo.toml
  ipld/amt/fuzz/fuzz_targets/amt_fuzz.rs
  ipld/blockstore/Cargo.toml
  ipld/car/Cargo.toml
  ipld/cid/Cargo.toml
  ipld/hamt/Cargo.toml
  ipld/hamt/fuzz/Cargo.toml
  ipld/hamt/fuzz/fuzz_targets/hamt_fuzz.rs
  node/db/Cargo.toml
  node/db/src/rocks.rs
  node/db/src/sled.rs
  node/db/tests/mem_test.rs
  node/db/tests/rocks_test.rs
  node/db/tests/sled_test.rs
  node/db/tests/subtests/mod.rs
  node/forest_libp2p/Cargo.toml
  node/rpc/Cargo.toml
  tests/conformance_tests/Cargo.toml
  types/Cargo.toml
  utils/bigint/Cargo.toml
  utils/bitfield/Cargo.toml
  utils/bitfield/benches/benchmarks/examples.rs
  utils/bitfield/benches/benchmarks/main.rs
  utils/bitfield/src/lib.rs
  utils/bitfield/tests/bitfield_tests.rs
  utils/commcid/Cargo.toml
  vm/Cargo.toml
  vm/actor/Cargo.toml
  vm/actor/tests/account_actor_test.rs
  vm/actor/tests/alpha_beta_filter_test.rs
  vm/actor/tests/balance_table_test.rs
  vm/actor/tests/common/mod.rs
  vm/actor/tests/cron_actor_test.rs
  vm/actor/tests/init_actor_test.rs
  vm/actor/tests/market_actor_test.rs
  vm/actor/tests/multimap_test.rs
  vm/actor/tests/paych_actor_test.rs
  vm/actor/tests/reward_actor_test.rs
  vm/actor/tests/set_multimap_test.rs
  vm/actor/tests/set_test.rs
  vm/interpreter/Cargo.toml
  vm/message/Cargo.toml
  vm/runtime/Cargo.toml
  vm/state_tree/Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#880 Fix message crate compilation with json feature
  Cargo.lock
  vm/message/Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#883 Remove coverage from CI until fixed
  .circleci/config.yml
  .gitmodules
  README.md
Labels: Status: Needs Review, Type: Maintenance

#882 Storage Miner Init Interop
  Cargo.lock
  blockchain/blocks/src/header/mod.rs
  blockchain/blocks/src/lib.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/message_pool/src/msgpool/mod.rs
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/utils.rs
  forest/dev.gen
  forest/src/daemon.rs
  node/rpc/Cargo.toml
  node/rpc/src/chain_api.rs
  node/rpc/src/gas_api.rs
  node/rpc/src/lib.rs
  node/rpc/src/state_api.rs
  node/rpc/src/sync_api.rs
  node/rpc/src/wallet_api.rs
Labels: Blockchain, Network, RPC, Status: Needs Review, Storage Miner

#884 Implement Net API Module + Some other RPC methods
  node/forest_libp2p/src/lib.rs
  node/forest_libp2p/src/service.rs
  node/rpc/Cargo.toml
  node/rpc/src/chain_api.rs
  node/rpc/src/lib.rs
  node/rpc/src/net_api.rs
  node/rpc/src/state_api.rs
Labels: RPC, Status: Needs Review, Storage Miner

#885 Update CI build checks
  .circleci/config.yml
Labels: Status: Needs Review, Type: Maintenance

#886 Update multisig to v2
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/multisig/state.rs
  vm/actor/src/builtin/multisig/types.rs
  vm/actor/src/builtin/system/mod.rs
Labels: Status: Needs Review, VM

#888 Update market actor to v2
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/market/policy.rs
  vm/actor/src/builtin/market/types.rs
Labels: Status: Needs Review, VM

#887 Version Hamt, Amt, State tree
  Cargo.lock
  Cargo.toml
  Makefile
  ipld/amt/Cargo.toml
  ipld/hamt/Cargo.toml
  ipld/hamt/src/hamt.rs
  ipld/hamt/src/lib.rs
  types/Cargo.toml
  types/src/lib.rs
  types/src/state.rs
  utils/hash_utils/Cargo.toml
  utils/hash_utils/src/key.rs
  utils/hash_utils/src/lib.rs
  vm/actor/Cargo.toml
  vm/actor/src/lib.rs
  vm/actor_interface/Cargo.toml
  vm/actor_interface/src/adt/array.rs
  vm/actor_interface/src/adt/map.rs
  vm/actor_interface/src/adt/mod.rs
  vm/actor_interface/src/lib.rs
  vm/interpreter/tests/transfer_test.rs
  vm/state_tree/Cargo.toml
  vm/state_tree/src/lib.rs
  vm/state_tree/tests/state_tree_tests.rs
Labels: Status: Needs Review, VM

#890 Update seal proof types and proofs api version
  Cargo.lock
  blockchain/state_manager/Cargo.toml
  types/Cargo.toml
  types/src/sector/registered_proof.rs
  vm/runtime/Cargo.toml
Labels: Status: Needs Review

#891 Handle pubsub blocks in parallel
  blockchain/chain_sync/src/sync.rs
Labels: Blockchain, Status: Merge Ready

#892 Add syncing configuration options
  blockchain/chain_sync/src/lib.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/chain_sync/src/sync_worker/full_sync_test.rs
  forest/src/cli/config.rs
  forest/src/cli/mod.rs
  forest/src/daemon.rs
  node/rpc/src/lib.rs
Labels: Status: Needs Review

#893 power actor v2 upgrade
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/policy.rs
  vm/actor/src/builtin/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/power/policy.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/builtin/power/types.rs
  vm/actor/src/builtin/sector.rs
Labels: Status: Needs Review, VM

#894 paych v2 actor update
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/paych/types.rs
  vm/actor/tests/paych_actor_test.rs
Labels: Status: Needs Review, VM

#895 Add a cfg flag to build Forest in Devnet mode
  Cargo.lock
  forest/Cargo.toml
  vm/actor/Cargo.toml
  vm/actor/src/builtin/miner/policy.rs
  vm/actor/src/builtin/sector.rs
  vm/actor/src/builtin/verifreg/types.rs
  vm/actor_interface/Cargo.toml
Labels: Status: Needs Review, VM

#889 Update verifreg actor to v2
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/verifreg/mod.rs
Labels: Status: Merge Ready, VM

#898 Add serde annotation for go vec visitor without using wrapper
  Cargo.lock
  utils/json_utils/Cargo.toml
  utils/json_utils/src/lib.rs
Labels: Status: Needs Review, Type: Enhancement

#899 Storage Miner Pledging
  Cargo.lock
  blockchain/state_manager/src/lib.rs
  node/rpc/src/chain_api.rs
  node/rpc/src/lib.rs
  node/rpc/src/mpool_api.rs
  node/rpc/src/state_api.rs
  vm/actor/src/builtin/miner/policy.rs
  vm/actor_interface/Cargo.toml
  vm/actor_interface/src/builtin/market/mod.rs
  vm/actor_interface/src/builtin/miner/mod.rs
  vm/actor_interface/src/builtin/mod.rs
  vm/actor_interface/src/builtin/power/mod.rs
  vm/actor_interface/src/builtin/reward/mod.rs
Labels: RPC, Status: Needs Review, Storage Miner

#896 Update runtime for network version upgrades
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/vm.rs
  vm/interpreter/tests/transfer_test.rs
Labels: Spec Change, Status: Needs Review

#900 Add GetMarketState to State Manager
  blockchain/state_manager/src/lib.rs
Labels: Status: Merge Ready

#897 Update reward actor to v2
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/types.rs
  vm/actor/src/builtin/reward/logic.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/builtin/reward/state.rs
  vm/actor/src/builtin/reward/types.rs
  vm/actor/tests/reward_actor_test.rs
Labels: Status: Needs Review, VM
