Repository ChainSafe/forest, pull requests merged in 2021-01, with the labels that each got.

#903 Update miner actor to v2
  Cargo.lock
  tests/conformance_tests/tests/conformance_runner.rs
  types/Cargo.toml
  types/src/version.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/market/types.rs
  vm/actor/src/builtin/miner/deadline_assignment.rs
  vm/actor/src/builtin/miner/deadline_state.rs
  vm/actor/src/builtin/miner/deadlines.rs
  vm/actor/src/builtin/miner/expiration_queue.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/monies.rs
  vm/actor/src/builtin/miner/partition_state.rs
  vm/actor/src/builtin/miner/policy.rs
  vm/actor/src/builtin/miner/sectors.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/miner/types.rs
  vm/actor/src/builtin/miner/vesting_state.rs
  vm/actor/src/builtin/reward/mod.rs
  vm/actor/src/lib.rs
  vm/actor/tests/reward_actor_test.rs
  vm/actor_interface/src/builtin/miner/mod.rs
  vm/actor_interface/src/lib.rs
Labels: Status: Needs Review, VM

#907 Replaced shared crates from actors with local versions
  Cargo.lock
  Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#906 Update types for all new V2 network upgrades
  Cargo.lock
  types/Cargo.toml
  types/src/version.rs
Labels: Status: Needs Review, Type: Maintenance

#911 Update randomness for conformance tipsets and update V7 proof verification
  Cargo.lock
  blockchain/state_manager/src/utils.rs
  blockchain/state_manager/src/vm_circ_supply.rs
  tests/conformance_tests/Cargo.toml
  tests/conformance_tests/src/lib.rs
  tests/conformance_tests/src/tipset.rs
  tests/conformance_tests/tests/conformance_runner.rs
  types/src/sector/registered_proof.rs
  vm/actor/src/builtin/miner/mod.rs
Labels: Spec Change, Status: Needs Review

#912 Update smoke base fee calculation
  blockchain/chain/src/store/base_fee.rs
Labels: Spec Change, Status: Needs Review

#914 Wrap ChainSyncer::state in an Arc<Mutex<_>> and set it to Follow accordingly
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync_worker.rs
Labels: Blockchain, Status: Needs Review

#915 Setup multiple network configurations and drand schedule
  Cargo.lock
  Cargo.toml
  Makefile
  blockchain/beacon/src/drand.rs
  blockchain/beacon/src/lib.rs
  blockchain/beacon/tests/drand.rs
  blockchain/blocks/src/header/mod.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/chain_sync/src/sync_worker/full_sync_test.rs
  blockchain/chain_sync/src/sync_worker/validate_block_test.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  forest/Cargo.toml
  forest/src/cli/config.rs
  forest/src/daemon.rs
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/config.rs
  node/rpc/src/beacon_api.rs
  node/rpc/src/common_api.rs
  node/rpc/src/lib.rs
  node/rpc/src/sync_api.rs
  types/networks/Cargo.toml
  types/networks/src/drand.rs
  types/networks/src/lib.rs
  types/networks/src/mainnet/genesis.car
  types/networks/src/mainnet/mod.rs
  types/src/build_version/mod.rs
  types/src/version.rs
  utils/genesis/Cargo.toml
  utils/genesis/src/export40.car
  utils/genesis/src/lib.rs
Labels: Blockchain, Status: Needs Review

#919 Calico (V7) update
  Cargo.lock
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/base_fee.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/message_pool/Cargo.toml
  blockchain/message_pool/src/msgpool/mod.rs
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/vm_circ_supply.rs
  node/rpc/Cargo.toml
  node/rpc/src/state_api.rs
  tests/conformance_tests/Cargo.toml
  tests/conformance_tests/src/message.rs
  types/networks/src/mainnet/mod.rs
  types/src/lib.rs
  types/src/sector/registered_proof.rs
  types/src/version.rs
  utils/genesis/src/lib.rs
  vm/interpreter/src/default_runtime.rs
  vm/message/src/unsigned_message.rs
Labels: Blockchain, Status: Needs Review, VM

#920 Claus fork burn removal
  Cargo.lock
  vm/actor_interface/src/builtin/mod.rs
  vm/interpreter/Cargo.toml
  vm/interpreter/src/vm.rs
Labels: Spec Change, Status: Needs Review, VM

#917 Update calico vesting and refactor circ supply
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/vm_circ_supply.rs
Labels: Blockchain, Status: Needs Review

#918 Update price list for calico VM gas
  vm/interpreter/src/gas_block_store.rs
  vm/interpreter/src/gas_tracker/price_list.rs
Labels: Status: Needs Review, VM

#924 Fix ChainNotify RPC
  blockchain/chain/src/store/chain_store.rs
  node/rpc/src/chain_api.rs
  node/rpc/src/lib.rs
  vm/message/src/unsigned_message.rs
Labels: RPC, Status: Needs Review

#922 Update libp2p, async-std, and other deps
  Cargo.lock
  blockchain/beacon/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/chain_sync/src/sync_worker/full_sync_test.rs
  blockchain/message_pool/src/msgpool/mod.rs
  blockchain/message_pool/src/msgpool/selection.rs
  forest/Cargo.toml
  forest/src/daemon.rs
  ipld/amt/Cargo.toml
  ipld/amt/fuzz/Cargo.toml
  ipld/car/Cargo.toml
  ipld/car/src/lib.rs
  ipld/cid/Cargo.toml
  ipld/graphsync/Cargo.toml
  ipld/hamt/Cargo.toml
  ipld/hamt/fuzz/Cargo.toml
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/hello/message.rs
  node/forest_libp2p/src/rpc/mod.rs
  node/forest_libp2p/src/service.rs
  node/rpc/Cargo.toml
  node/rpc/src/lib.rs
  node/rpc/src/net_api.rs
  node/rpc/src/sync_api.rs
  tests/serialization_tests/tests/block_header_ser.rs
  tests/serialization_tests/tests/u_message_ser.rs
  utils/bitfield/Cargo.toml
  utils/net_utils/Cargo.toml
  utils/paramfetch/Cargo.toml
  utils/paramfetch/src/lib.rs
  vm/actor/Cargo.toml
  vm/actor_interface/Cargo.toml
  vm/interpreter/Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#929 Clean up chain exchange responses and peer disconnects
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/peer_manager.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/chain_sync/src/sync_worker/full_sync_test.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/rpc/mod.rs
  node/forest_libp2p/src/service.rs
Labels: Status: Needs Review, Type: Enhancement

#931 Switch temp bytes deserialize to Cow
  crypto/src/signature.rs
  ipld/amt/src/bitmap.rs
  utils/bigint/src/bigint_ser.rs
  utils/bigint/src/biguint_ser.rs
  utils/bitfield/src/rleplus/mod.rs
  vm/address/src/lib.rs
Labels: Status: Needs Review

#930 Update header caches and builder
  Cargo.lock
  blockchain/blocks/Cargo.toml
  blockchain/blocks/src/header/json.rs
  blockchain/blocks/src/header/mod.rs
  blockchain/blocks/src/tipset.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/bucket.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/message_pool/src/msgpool/mod.rs
  node/rpc/src/state_api.rs
  utils/test_utils/src/chain_structures.rs
Labels: Status: Needs Review, Type: Enhancement

#935 Fix header signing bytes cache bug
  blockchain/blocks/src/header/mod.rs
  blockchain/chain_sync/src/sync_worker.rs
  node/rpc/src/state_api.rs
Labels: Status: Needs Review, Type: Bug

#932 CBOR Stream Read in LibP2P RPC
  Cargo.lock
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/rpc/mod.rs
  node/forest_libp2p/src/service.rs
Labels: Network, Status: Needs Review

#941 Fix typo in calico winning post validation
  blockchain/state_manager/src/utils.rs
Labels: Status: Needs Review, Type: Bug

#940 Update calico storage gas multiplier
  vm/interpreter/src/gas_tracker/gas_charge.rs
  vm/interpreter/src/gas_tracker/price_list.rs
Labels: Status: Needs Review, Type: Bug

#946 Update consensus min power
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/builtin/sector.rs
Labels: Spec Change, Status: Needs Review, Type: Bug

#943 Fix bug with pledge delta from proving deadline
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/state.rs
Labels: Status: Needs Review, Type: Bug

#942 Fix calico vesting
  blockchain/state_manager/src/vm_circ_supply.rs
Labels: Status: Needs Review, Type: Bug

#947 Nullable Entropy in Randomness RPC and Fix Gas Base Fee Estimation
  node/rpc/src/chain_api.rs
  node/rpc/src/gas_api.rs
  node/rpc/src/wallet_api.rs
Labels: RPC, Status: Needs Review

#950 Fix bugs in terminate sectors logic
  vm/actor/src/builtin/miner/expiration_queue.rs
  vm/actor/src/builtin/miner/partition_state.rs
Labels: Status: Needs Review, Type: Bug

#951 Ignore invalid peer id in miner info
  vm/actor_interface/src/builtin/miner/mod.rs
Labels: Status: Needs Review

#953 Handle null multisig proposal hashes
  vm/actor/src/builtin/multisig/mod.rs
Labels: Status: Needs Review, Type: Bug

#945 Update bls backend to blst
  Cargo.lock
  blockchain/beacon/Cargo.toml
  blockchain/beacon/src/drand.rs
  blockchain/state_manager/Cargo.toml
  crypto/Cargo.toml
  crypto/src/signature.rs
  key_management/Cargo.toml
  node/rpc/Cargo.toml
  tests/serialization_tests/Cargo.toml
  types/Cargo.toml
  vm/runtime/Cargo.toml
Labels: Type: Enhancement

#949 Update statediff for v2 and keep under feature
  Cargo.lock
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  utils/statediff/Cargo.toml
  utils/statediff/src/lib.rs
  vm/state_tree/src/lib.rs
Labels: Status: Needs Review, Type: Enhancement

#948 Fix storage deal resolution pattern
  vm/actor/src/builtin/market/mod.rs
Labels: Status: Needs Review, Type: Bug

#952 Fix to address resolution for chained internal calls
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/vm.rs
  vm/interpreter/tests/transfer_test.rs
Labels: Status: Needs Review, Type: Bug

#939 Add skip-load flag and cleanup snapshot loading
  blockchain/chain/src/store/chain_store.rs
  forest/src/cli/config.rs
  forest/src/cli/mod.rs
  forest/src/daemon.rs
  ipld/car/src/lib.rs
  utils/genesis/src/lib.rs
Labels: Status: Needs Review, Type: Bug

#954 Update logging to hide internal messages by default
  vm/actor/src/builtin/power/mod.rs
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/vm.rs
Labels: Status: Needs Review, Type: Maintenance

#933 Cleanup TODOs
  blockchain/blocks/tests/ticket_test.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/tipset_tracker.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/message_pool/src/lib.rs
  blockchain/message_pool/src/msg_chain.rs
  blockchain/message_pool/src/msgpool/mod.rs
  blockchain/message_pool/src/msgpool/selection.rs
  forest/src/cli/fetch_params_cmd.rs
  forest/src/daemon.rs
  key_management/src/wallet.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/chain_exchange/message.rs
  node/rpc/src/gas_api.rs
  node/rpc/src/sync_api.rs
  tests/conformance_tests/src/tipset.rs
  vm/actor/src/builtin/cron/state.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/miner/types.rs
  vm/actor/src/util/chaos/mod.rs
  vm/actor/src/util/downcast.rs
  vm/actor/tests/common/mod.rs
  vm/actor_interface/src/builtin/miner/mod.rs
  vm/interpreter/src/default_runtime.rs
Labels: Status: Needs Review, Type: Maintenance

#967 Purge approvals on multisig removal
  vm/actor/src/builtin/multisig/mod.rs
Labels: Status: Needs Review, Type: Bug

#965 Fixes to ChainSyncer Scheduling
  blockchain/blocks/src/header/mod.rs
  blockchain/chain_sync/src/bucket.rs
  blockchain/chain_sync/src/sync.rs
  node/forest_libp2p/Cargo.toml
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/service.rs
Labels: Blockchain, Network, Status: Needs Changes

#968 Fix edge case in update pending deal state
  vm/actor/src/builtin/market/state.rs
Labels: Status: Needs Review, Type: Bug

#969 Remove irrelevant spam logs
  blockchain/chain_sync/src/sync.rs
  blockchain/message_pool/src/msgpool/mod.rs
  forest/src/logger/mod.rs
  node/forest_libp2p/src/service.rs
Labels: Status: Needs Review, Type: Maintenance

#971 Fix Gossip Syncing for Blocks at Same Epoch
  blockchain/chain_sync/src/sync_worker.rs
Labels: Blockchain, Status: Needs Review

#972 Fix block header signature verification helper function
  blockchain/blocks/src/header/mod.rs
  blockchain/chain_sync/src/sync_worker.rs
Labels: Status: Needs Review, Type: Bug
