Repository ChainSafe/forest, pull requests merged in 2021-02, with the labels that each got.

#976 Replace lazycell with once_cell
  Cargo.lock
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/vm_circ_supply.rs
  ipld/amt/Cargo.toml
  ipld/amt/src/node.rs
  ipld/hamt/Cargo.toml
  ipld/hamt/src/node.rs
  ipld/hamt/src/pointer.rs
  utils/paramfetch/src/lib.rs
Labels: Status: Needs Review, Type: Maintenance

#973 Fix verify consensus fault logic
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/monies.rs
  vm/interpreter/src/default_runtime.rs
Labels: Status: Needs Review, Type: Bug

#955 Replace broadcast channels and refactor websocket streaming
  Cargo.lock
  blockchain/beacon/Cargo.toml
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/message_pool/Cargo.toml
  blockchain/message_pool/src/msgpool/mod.rs
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  forest/Cargo.toml
  forest/src/daemon.rs
  ipld/Cargo.toml
  ipld/car/Cargo.toml
  ipld/graphsync/Cargo.toml
  node/forest_libp2p/Cargo.toml
  node/rpc/Cargo.toml
  node/rpc/src/chain_api.rs
  node/rpc/src/lib.rs
  node/rpc/src/sync_api.rs
  tests/conformance_tests/Cargo.toml
  types/Cargo.toml
  utils/genesis/Cargo.toml
  utils/net_utils/Cargo.toml
  utils/paramfetch/Cargo.toml
  utils/test_utils/Cargo.toml
Labels: Status: Needs Review, Type: Enhancement

#975 Refactor discovery, improve Hello handling/peer management
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/peer_manager.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/chain_sync/src/sync_worker/full_sync_test.rs
  blockchain/message_pool/src/msgpool/selection.rs
  forest/src/cli/mod.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/config.rs
  node/forest_libp2p/src/discovery.rs
  node/forest_libp2p/src/hello/message.rs
  node/forest_libp2p/src/lib.rs
  node/forest_libp2p/src/service.rs
Labels: Network, Status: Needs Review, Type: Enhancement

#979 Update Amt API and prep release
  Cargo.lock
  blockchain/chain_sync/src/lib.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/state_manager/src/lib.rs
  ipld/amt/Cargo.toml
  ipld/amt/benches/amt_benchmark.rs
  ipld/amt/src/amt.rs
  ipld/amt/src/node.rs
  node/rpc/src/state_api.rs
Labels: Status: Needs Review, Type: Maintenance

#978 v3 Actors Amt update
  Cargo.lock
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/Cargo.toml
  blockchain/state_manager/Cargo.toml
  blockchain/state_manager/src/lib.rs
  encoding/src/bytes.rs
  ipld/amt/CHANGELOG.md
  ipld/amt/Cargo.toml
  ipld/amt/benches/amt_benchmark.rs
  ipld/amt/fuzz/fuzz_targets/amt_fuzz.rs
  ipld/amt/src/amt.rs
  ipld/amt/src/bitmap.rs
  ipld/amt/src/error.rs
  ipld/amt/src/lib.rs
  ipld/amt/src/node.rs
  ipld/amt/src/root.rs
  ipld/amt/tests/amt_tests.rs
  node/rpc/Cargo.toml
  vm/actor/Cargo.toml
Labels: Spec Change, Status: Needs Review

#980 Fix fork handling
  blockchain/chain_sync/src/sync_worker.rs
Labels: Status: Merge Ready

#981 Prep hamt v2 release
  Cargo.lock
  ipld/hamt/CHANGELOG.md
  ipld/hamt/Cargo.toml
  ipld/hamt/src/node.rs
  ipld/hamt/src/pointer.rs
  ipld/hamt/tests/hamt_tests.rs
  utils/statediff/Cargo.toml
  vm/actor/Cargo.toml
  vm/interpreter/Cargo.toml
  vm/state_tree/Cargo.toml
Labels: Status: Needs Review, Type: Maintenance

#983 Nightly build/audit workaround and nightly linting fixes
  .circleci/config.yml
  blockchain/blocks/src/header/json.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain_sync/src/bucket.rs
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/message_pool/src/msgpool/mod.rs
  blockchain/message_pool/src/msgpool/selection.rs
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/utils.rs
  forest/src/cli/genesis_cmd.rs
  ipld/hamt/src/pointer.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/chain_exchange/message.rs
  node/forest_libp2p/src/discovery.rs
  node/forest_libp2p/src/service.rs
  node/rpc/src/lib.rs
  vm/actor/src/builtin/miner/expiration_queue.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/util/set.rs
  vm/address/src/lib.rs
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/gas_block_store.rs
  vm/state_tree/src/lib.rs
Labels: Status: Needs Review, Type: Maintenance

#989 Fix bug in miner extend sector expiration
  vm/actor/src/builtin/miner/mod.rs
Labels: Status: Needs Review, Type: Bug

#982 v3 Hamt update
  Cargo.lock
  ipld/hamt/CHANGELOG.md
  ipld/hamt/Cargo.toml
  ipld/hamt/benches/hamt_benchmark.rs
  ipld/hamt/src/hamt.rs
  ipld/hamt/src/node.rs
  ipld/hamt/src/pointer.rs
  ipld/hamt/tests/hamt_tests.rs
Labels: Spec Change, Status: Needs Review

#991 fix hyper vulnerability
  Cargo.lock
Labels: Status: Needs Review, Type: Maintenance

#988 Improve Car file read node
  ipld/car/src/util.rs
Labels: Status: Needs Review, Type: Enhancement

#987 Framework for State Migrations
  types/networks/src/interopnet/mod.rs
  types/networks/src/lib.rs
  types/networks/src/mainnet/mod.rs
  types/src/version.rs
  vm/interpreter/src/vm.rs
Labels: Status: Needs Review, VM

#993 Add 1.46.0 msrv check to CI
  .circleci/config.yml
  README.md
Labels: Status: Needs Review, Type: Maintenance

#1001 Actors v3 Setup
  Cargo.lock
  types/src/state.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/account/mod.rs
  vm/actor/src/builtin/codes.rs
  vm/actor/src/builtin/cron/mod.rs
  vm/actor/src/builtin/system/mod.rs
  vm/actor_interface/Cargo.toml
  vm/actor_interface/src/adt/array.rs
  vm/actor_interface/src/adt/map.rs
  vm/actor_interface/src/builtin/account/mod.rs
  vm/actor_interface/src/builtin/cron/mod.rs
  vm/actor_interface/src/builtin/mod.rs
  vm/actor_interface/src/builtin/system/mod.rs
  vm/actor_interface/src/lib.rs
  vm/interpreter/src/default_runtime.rs
  vm/state_tree/src/lib.rs
Labels: Status: Needs Review, VM

#1000 Blockchain docs and cleanup
  blockchain/beacon/src/beacon_entries.rs
  blockchain/beacon/src/drand.rs
  blockchain/beacon/src/mock_beacon.rs
  blockchain/blocks/src/block.rs
  blockchain/blocks/src/gossip_block.rs
  blockchain/blocks/src/ticket.rs
  blockchain/blocks/src/tipset.rs
  blockchain/chain/Cargo.toml
  blockchain/chain/src/store/base_fee.rs
  blockchain/chain/src/store/chain_store.rs
  blockchain/chain/src/store/index.rs
  blockchain/chain/src/store/mod.rs
  blockchain/chain/src/store/tipset_tracker.rs
  blockchain/chain_sync/src/bad_block_cache.rs
  blockchain/chain_sync/src/bucket.rs
  blockchain/chain_sync/src/lib.rs
  blockchain/chain_sync/src/network_context.rs
  blockchain/chain_sync/src/peer_manager.rs
  blockchain/chain_sync/src/sync.rs
  blockchain/chain_sync/src/sync/peer_test.rs
  blockchain/chain_sync/src/sync_state.rs
  blockchain/chain_sync/src/sync_worker.rs
  blockchain/message_pool/src/block_prob.rs
  blockchain/message_pool/src/config.rs
  blockchain/message_pool/src/errors.rs
  blockchain/message_pool/src/msgpool/mod.rs
  blockchain/state_manager/src/chain_rand.rs
  blockchain/state_manager/src/lib.rs
  blockchain/state_manager/src/utils.rs
  blockchain/state_manager/src/vm_circ_supply.rs
  key_management/src/keystore.rs
  node/rpc/src/state_api.rs
  utils/test_utils/src/chain_structures.rs
Labels: Status: Needs Review, Type: Maintenance

#1002 Update crypto docs and cleanup API
  crypto/CHANGELOG.md
  crypto/src/randomness.rs
  crypto/src/signature.rs
  crypto/src/signer.rs
  crypto/src/vrf.rs
Labels: Status: Needs Review, Type: Maintenance

#1004 Update ipld docs
  ipld/blockstore/src/lib.rs
  ipld/blockstore/src/resolve.rs
  ipld/blockstore/src/tracking.rs
  ipld/cid/src/lib.rs
  ipld/hamt/src/hash_algorithm.rs
Labels: Status: Needs Review, Type: Maintenance

#1005 V3 HAMT and AMT for Actors
  Cargo.lock
  utils/bigint/src/bigint_ser.rs
  vm/actor/Cargo.toml
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/miner/bitfield_queue.rs
  vm/actor/src/builtin/miner/deadline_state.rs
  vm/actor/src/builtin/miner/deadlines.rs
  vm/actor/src/builtin/miner/expiration_queue.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/miner/partition_state.rs
  vm/actor/src/builtin/miner/sector_map.rs
  vm/actor/src/builtin/miner/sectors.rs
  vm/actor/src/builtin/miner/state.rs
  vm/actor/src/builtin/miner/types.rs
  vm/actor/src/builtin/paych/mod.rs
  vm/actor/src/builtin/paych/state.rs
  vm/actor/src/builtin/paych/types.rs
  vm/actor/src/builtin/power/policy.rs
  vm/actor/src/builtin/power/state.rs
  vm/actor/src/util/balance_table.rs
  vm/actor/src/util/multimap.rs
  vm/actor/src/util/set.rs
  vm/actor/src/util/set_multimap.rs
  vm/actor/tests/multimap_test.rs
  vm/actor/tests/paych_actor_test.rs
  vm/actor_interface/Cargo.toml
  vm/actor_interface/src/adt/array.rs
  vm/actor_interface/src/adt/map.rs
Labels: Status: Needs Review, VM

#1009 Update VM docs.
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/gas_tracker/gas_charge.rs
  vm/interpreter/src/gas_tracker/mod.rs
  vm/interpreter/src/gas_tracker/price_list.rs
  vm/interpreter/src/vm.rs
  vm/message/src/lib.rs
  vm/message/src/signed_message.rs
  vm/runtime/src/lib.rs
  vm/src/actor_state.rs
  vm/src/exit_code.rs
  vm/src/invoc.rs
  vm/src/lib.rs
  vm/src/method.rs
  vm/src/token.rs
  vm/state_tree/src/lib.rs
Labels: Status: Needs Review, Type: Maintenance

#1011 Fix new clippy warnings and fix logic
  blockchain/state_manager/src/vm_circ_supply.rs
  vm/interpreter/src/vm.rs
Labels: Status: Needs Review, Type: Maintenance

#1008 Update types documentation
  blockchain/message_pool/src/msgpool/selection.rs
  types/networks/src/interopnet/mod.rs
  types/networks/src/mainnet/mod.rs
  types/src/build_version/mod.rs
  types/src/deadlines/mod.rs
  types/src/deadlines/quantize.rs
  types/src/genesis/mod.rs
  types/src/lib.rs
  types/src/piece/mod.rs
  types/src/piece/zero.rs
  types/src/randomness.rs
  types/src/sector/mod.rs
  types/src/sector/post.rs
  types/src/sector/registered_proof.rs
  types/src/sector/seal.rs
  types/src/state.rs
  types/src/verifier/mock.rs
  types/src/verifier/mod.rs
  vm/interpreter/src/default_runtime.rs
  vm/interpreter/src/vm.rs
Labels: Status: Needs Review, Type: Maintenance

#1010 Market Actor v3
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/market/mod.rs
  vm/actor/src/builtin/market/state.rs
  vm/actor/src/builtin/market/types.rs
  vm/actor/src/builtin/miner/mod.rs
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/power/mod.rs
  vm/actor/src/builtin/verifreg/mod.rs
  vm/actor/src/lib.rs
  vm/actor/src/util/balance_table.rs
  vm/actor/src/util/mod.rs
  vm/actor/src/util/multimap.rs
  vm/actor/src/util/set.rs
  vm/actor/src/util/set_multimap.rs
  vm/actor/tests/market_actor_test.rs
  vm/actor_interface/src/adt/map.rs
Labels: Status: Needs Review, VM

#1013 Multisig Actor v3
  vm/actor/src/builtin/multisig/mod.rs
  vm/actor/src/builtin/multisig/state.rs
  vm/actor/src/lib.rs
Labels: Status: Needs Review, VM

#1007 Document node and cleanup
  Cargo.toml
  blockchain/chain_sync/src/network_context.rs
  blockchain/message_pool/src/msgpool/mod.rs
  node/clock/src/lib.rs
  node/clock/tests/clock_test.rs
  node/db/src/rocks.rs
  node/db/src/sled.rs
  node/forest_libp2p/src/behaviour.rs
  node/forest_libp2p/src/chain_exchange/message.rs
  node/forest_libp2p/src/chain_exchange/mod.rs
  node/forest_libp2p/src/chain_exchange/provider.rs
  node/forest_libp2p/src/config.rs
  node/forest_libp2p/src/hello/message.rs
  node/forest_libp2p/src/hello/mod.rs
  node/forest_libp2p/src/lib.rs
  node/forest_libp2p/src/rpc/mod.rs
  node/forest_libp2p/src/service.rs
Labels: Status: Needs Review, Type: Maintenance

#1016 Verifreg Actor v3
  vm/actor/src/builtin/verifreg/mod.rs
  vm/actor/src/builtin/verifreg/state.rs
  vm/actor/src/lib.rs
Labels: Status: Needs Review, VM

#1018 Remove old codeowners
  .github/CODEOWNERS
Labels: Status: Needs Review, Type: Maintenance

#1019 Init Actor v3
  vm/actor/src/builtin/init/mod.rs
  vm/actor/src/builtin/init/state.rs
  vm/actor/src/builtin/multisig/mod.rs
Labels: Status: Needs Review, VM

#1020 Reward Actor v3
  vm/actor/src/builtin/reward/mod.rs
Labels: Status: Needs Review, VM
